// Copyright 2024 Diversion Company, Inc. All Rights Reserved.
/**
 * Diversion Core API
 * Definition of the Core API used to access low-level functionality of Diversion
 *
 * The version of the OpenAPI document: 0.2.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.10.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#pragma once

#include "CoreMinimal.h"
#include "HTTPResult.h"
#include "DiversionHttpManager.h"
#include "Misc/TVariant.h"


#include "AnalyticsEvents.h"

namespace Diversion {
namespace CoreAPI {

using namespace Diversion::CoreAPI::Model;

class COREAPI_API AnalyticsApi
{
public:
    explicit AnalyticsApi(TSharedPtr<DiversionHttp::FHttpRequestManager> ApiClient);
    virtual ~AnalyticsApi();


    /**
    * Ingest analytics events
    * @param analyticsEvents 
    * 
    */
    THTTPResult<TVariant<void*>> SrcHandlersAnalyticsIngest(
        TSharedPtr<AnalyticsEvents> analyticsEvents,
        const FString& Token,
        const TMap<FString, FString>& Headers,
		int ConnectionTimeoutSeconds, int RequestTimeoutSeconds) const;

    typedef FApiResponseDelegate<TVariant<void*>> Fsrc_handlers_analytics_ingestDelegate;

protected:
    TSharedPtr<DiversionHttp::FHttpRequestManager> ApiClient;
};

}
}

