// Copyright 2024 Diversion Company, Inc. All Rights Reserved.
/**
 * Diversion Core API
 * Definition of the Core API used to access low-level functionality of Diversion
 *
 * The version of the OpenAPI document: 0.2.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.10.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * AnalyticsEvents.h
 *
 * A list of analytics events
 */
#pragma once


#include "ModelBase.h"
#include "AnalyticsEvent.h"

namespace Diversion {
namespace CoreAPI {
namespace Model {

class AnalyticsEvent;

/*
 * AnalyticsEvents
 *
 * A list of analytics events
 */
class COREAPI_API AnalyticsEvents
    : public Model
{
public:
    virtual ~AnalyticsEvents() {}

	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) override;
	void WriteJson(JsonWriter& Writer) const override;


	TArray<AnalyticsEvent> mEvents;

};


}
}
}

