// Copyright 2024 Diversion Company, Inc. All Rights Reserved.
/**
 * Diversion Core API
 * Definition of the Core API used to access low-level functionality of Diversion
 *
 * The version of the OpenAPI document: 0.2.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.10.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * BlobUploadUrl.h
 *
 * 
 */
#pragma once


#include "ModelBase.h"
#include "BlobLocation.h"
#include "PresignedUploadUrl.h"

namespace Diversion {
namespace CoreAPI {
namespace Model {

class BlobLocation;
class PresignedUploadUrl;

/*
 * BlobUploadUrl
 *
 * 
 */
class COREAPI_API BlobUploadUrl
    : public Model
{
public:
    virtual ~BlobUploadUrl() {}

	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) override;
	void WriteJson(JsonWriter& Writer) const override;


	BlobLocation mLocation;

	TOptional<PresignedUploadUrl> mUpload_url;

};


}
}
}

