// Copyright 2024 Diversion Company, Inc. All Rights Reserved.
/**
 * Diversion Core API
 * Definition of the Core API used to access low-level functionality of Diversion
 *
 * The version of the OpenAPI document: 0.2.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.10.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * Branch.h
 *
 * 
 */
#pragma once


#include "ModelBase.h"
#include "User.h"

namespace Diversion {
namespace CoreAPI {
namespace Model {

class User;

/*
 * Branch
 *
 * 
 */
class COREAPI_API Branch
    : public Model
{
public:
    virtual ~Branch() {}

	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) override;
	void WriteJson(JsonWriter& Writer) const override;


	FString mCommit_id;

	FString mBranch_name;

	TOptional<FString> mBranch_description;

	/* Branch identifier in Diversion */
	FString mBranch_id;

	User mAuthor;

	/* Creation time */
	double mTime = 0.0;

};


}
}
}

