// Copyright 2024 Diversion Company, Inc. All Rights Reserved.
/**
 * Diversion Core API
 * Definition of the Core API used to access low-level functionality of Diversion
 *
 * The version of the OpenAPI document: 0.2.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.10.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * ClientUpdates.h
 *
 * A list of updates sent by the client
 */
#pragma once


#include "ModelBase.h"
#include "ClientUpdate.h"

namespace Diversion {
namespace CoreAPI {
namespace Model {

class ClientUpdate;

/*
 * ClientUpdates
 *
 * A list of updates sent by the client
 */
class COREAPI_API ClientUpdates
    : public Model
{
public:
    virtual ~ClientUpdates() {}

	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) override;
	void WriteJson(JsonWriter& Writer) const override;


	TArray<ClientUpdate> mUpdates;

};


}
}
}

