// Copyright 2024 Diversion Company, Inc. All Rights Reserved.
/**
 * Diversion Core API
 * Definition of the Core API used to access low-level functionality of Diversion
 *
 * The version of the OpenAPI document: 0.2.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.10.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * ClientUpdateResult.h
 *
 * A single update result returned to the client
 */
#pragma once


#include "ModelBase.h"

namespace Diversion {
namespace CoreAPI {
namespace Model {


/*
 * ClientUpdateResult
 *
 * A single update result returned to the client
 */
class COREAPI_API ClientUpdateResult
    : public Model
{
public:
    virtual ~ClientUpdateResult() {}

	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) override;
	void WriteJson(JsonWriter& Writer) const override;


	FString mTransaction_id;

	bool mSuccess = false;

	TOptional<FString> mError_msg;

	TOptional<int32_t> mStatus_code;

};


}
}
}

