// Copyright 2024 Diversion Company, Inc. All Rights Reserved.
/**
 * Diversion Core API
 * Definition of the Core API used to access low-level functionality of Diversion
 *
 * The version of the OpenAPI document: 0.2.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.10.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * CollaborationInviteRequest.h
 *
 * 
 */
#pragma once


#include "ModelBase.h"

namespace Diversion {
namespace CoreAPI {
namespace Model {


/*
 * CollaborationInviteRequest
 *
 * 
 */
class COREAPI_API CollaborationInviteRequest
    : public Model
{
public:
    virtual ~CollaborationInviteRequest() {}

	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) override;
	void WriteJson(JsonWriter& Writer) const override;


	/* A user ID or email. User IDs are preferred, but an email can be used to invite a new collaborator who does not have an account or whose user ID is unknown.  */
	FString mCollaborator_handle;

	FString mMode;

};


}
}
}

