// Copyright 2024 Diversion Company, Inc. All Rights Reserved.
/**
 * Diversion Core API
 * Definition of the Core API used to access low-level functionality of Diversion
 *
 * The version of the OpenAPI document: 0.2.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.10.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * CollaborationInvite.h
 *
 * 
 */
#pragma once


#include "ModelBase.h"

namespace Diversion {
namespace CoreAPI {
namespace Model {


/*
 * CollaborationInvite
 *
 * 
 */
class COREAPI_API CollaborationInvite
    : public Model
{
public:
    virtual ~CollaborationInvite() {}

	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) override;
	void WriteJson(JsonWriter& Writer) const override;


	int32_t mInvite_id = 0;

	FString mInviting_user_id;

	FString mInvited_email;

	FString mAccess_mode;

	FDateTime mCreated;

	FDateTime mExpires;

};


}
}
}

