// Copyright 2024 Diversion Company, Inc. All Rights Reserved.
/**
 * Diversion Core API
 * Definition of the Core API used to access low-level functionality of Diversion
 *
 * The version of the OpenAPI document: 0.2.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.10.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * Conflict.h
 *
 * 
 */
#pragma once


#include "ModelBase.h"
#include "ConflictIndex.h"

namespace Diversion {
namespace CoreAPI {
namespace Model {

class ConflictIndex;

/*
 * Conflict
 *
 * 
 */
class COREAPI_API Conflict
    : public Model
{
public:
    virtual ~Conflict() {}

	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) override;
	void WriteJson(JsonWriter& Writer) const override;


	FString mConflict_id;

	bool mIs_resolved = false;

	enum class Resolved_sideEnum
	{
		RESULT,
		BASE,
		OTHER,
  	};

	static FString EnumToString(const TOptional<Resolved_sideEnum>& EnumValue);
	static bool EnumFromString(const FString& EnumAsString, TOptional<Resolved_sideEnum>& EnumValue);
	TOptional<Resolved_sideEnum> mResolved_side;

	ConflictIndex mBase;

	ConflictIndex mOther;

	TOptional<ConflictIndex> mResult;

};


}
}
}

