// Copyright 2024 Diversion Company, Inc. All Rights Reserved.
/**
 * Diversion Core API
 * Definition of the Core API used to access low-level functionality of Diversion
 *
 * The version of the OpenAPI document: 0.2.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.10.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * CreateShelf.h
 *
 * 
 */
#pragma once


#include "ModelBase.h"

namespace Diversion {
namespace CoreAPI {
namespace Model {


/*
 * CreateShelf
 *
 * 
 */
class COREAPI_API CreateShelf
    : public Model
{
public:
    virtual ~CreateShelf() {}

	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) override;
	void WriteJson(JsonWriter& Writer) const override;


	/* Display name of the shelf */
	FString mName;

	/* Workspace ID from which to shelve changes */
	FString mWorkspace_id;

	/* Should reset workspace changes after creating the shelf */
	TOptional<bool> mReset_workspace;

};


}
}
}

