// Copyright 2024 Diversion Company, Inc. All Rights Reserved.
/**
 * Diversion Core API
 * Definition of the Core API used to access low-level functionality of Diversion
 *
 * The version of the OpenAPI document: 0.2.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.10.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * ErrorReport.h
 *
 * 
 */
#pragma once


#include "ModelBase.h"

namespace Diversion {
namespace CoreAPI {
namespace Model {


/*
 * ErrorReport
 *
 * 
 */
class COREAPI_API ErrorReport
    : public Model
{
public:
    virtual ~ErrorReport() {}

	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) override;
	void WriteJson(JsonWriter& Writer) const override;


	/* Name of the source of the error */
	TOptional<FString> mSource;

	/* Error message */
	TOptional<FString> mError;

	/* Stack trace */
	TOptional<FString> mStack;

};


}
}
}

