// Copyright 2024 Diversion Company, Inc. All Rights Reserved.
/**
 * Diversion Core API
 * Definition of the Core API used to access low-level functionality of Diversion
 *
 * The version of the OpenAPI document: 0.2.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.10.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * Inline_object_5.h
 *
 * 
 */
#pragma once


#include "ModelBase.h"
#include "Tag.h"

namespace Diversion {
namespace CoreAPI {
namespace Model {

class Tag;

/*
 * Inline_object_5
 *
 * 
 */
class COREAPI_API Inline_object_5
    : public Model
{
public:
    virtual ~Inline_object_5() {}

	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) override;
	void WriteJson(JsonWriter& Writer) const override;


	enum class ObjectEnum
	{
		TAG,
  	};

	static FString EnumToString(const ObjectEnum& EnumValue);
	static bool EnumFromString(const FString& EnumAsString, ObjectEnum& EnumValue);
	ObjectEnum mobject;

	TArray<Tag> mItems;

};


}
}
}

