// Copyright 2024 Diversion Company, Inc. All Rights Reserved.
/**
 * Diversion Core API
 * Definition of the Core API used to access low-level functionality of Diversion
 *
 * OpenAPI spec version: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "OpenAPIBaseModel.h"
#include "OpenAPIJournalEntry.h"

namespace CoreAPI
{

/*
 * OpenAPIWorkspaceUpdates
 *
 * A list of modification operations done on the workspace.
 */
class COREAPI_API OpenAPIWorkspaceUpdates : public Model
{
public:
    virtual ~OpenAPIWorkspaceUpdates() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	TArray<OpenAPIJournalEntry> Journal;
	/* Latest commit the workspace is checkout out on */
	TOptional<FString> CommitId;
	/* Which branch the workspace is checked out on, or none if detached */
	TOptional<FString> BranchId;
	/* The commit ID the workspace is based on, whether checket out on branch or commit */
	FString BaseCommitId;
	/* More results are available, call the endpoint again with the latest revision from this response */
	bool IncompleteResponse = false;
};

}
