// Copyright 2024 Diversion Company, Inc. All Rights Reserved.
/**
 * Diversion Core API
 * Definition of the Core API used to access low-level functionality of Diversion
 *
 * OpenAPI spec version: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "OpenAPIBaseModel.h"

namespace CoreAPI
{

/*
 * OpenAPIResetStatus
 *
 * Response of a reset command.
 */
class COREAPI_API OpenAPIResetStatus : public Model
{
public:
    virtual ~OpenAPIResetStatus() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	/* Paths that were successfully reset. */
	TArray<FString> Success;
	/* Paths that were not found. */
	TArray<FString> Fail;
	/* Paths that were not reset. */
	TArray<FString> Skipped;
};

}
