// Copyright 2024 Diversion Company, Inc. All Rights Reserved.
/**
 * Diversion Core API
 * Definition of the Core API used to access low-level functionality of Diversion
 *
 * OpenAPI spec version: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "OpenAPIBaseModel.h"
#include "OpenAPIAccessMode.h"

namespace CoreAPI
{

/*
 * OpenAPICollaborationInviteRequest
 *
 * 
 */
class COREAPI_API OpenAPICollaborationInviteRequest : public Model
{
public:
    virtual ~OpenAPICollaborationInviteRequest() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	/* A user ID or email. User IDs are preferred, but an email can be used to invite a new collaborator who does not have an account or whose user ID is unknown.  */
	FString CollaboratorHandle;
	OpenAPIAccessMode Mode;
};

}
