// Copyright 2024 Diversion Company, Inc. All Rights Reserved.
/**
 * Diversion Core API
 * Definition of the Core API used to access low-level functionality of Diversion
 *
 * OpenAPI spec version: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "OpenAPIBaseModel.h"

namespace CoreAPI
{

/*
 * OpenAPIConflictIndex
 *
 * A index in a conflict, could be representing either \&quot;base\&quot;, \&quot;other\&quot; or \&quot;result\&quot;. If the index does not represent \&quot;result\&quot;, then all properties besides \&quot;prev_path\&quot; can be considered &#39;required&#39;. 
 */
class COREAPI_API OpenAPIConflictIndex : public Model
{
public:
    virtual ~OpenAPIConflictIndex() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	enum class ConflictIndexIdEnum
	{
		Result,
		Base,
		Other,
  	};

	static FString EnumToString(const ConflictIndexIdEnum& EnumValue);
	static bool EnumFromString(const FString& EnumAsString, ConflictIndexIdEnum& EnumValue);
	ConflictIndexIdEnum ConflictIndexId;
	int32 FileMode = 0;
	FString Path;
	TOptional<FString> PrevPath;
	int32 Type = 0;
	TOptional<int32> StorageBackend;
	/* Coupled with storage_backend, a uri to storage location */
	TOptional<FString> StorageUri;
	/* Size in bytes */
	TOptional<int64> Size;
};

}
