// Copyright 2024 Diversion Company, Inc. All Rights Reserved.
/**
 * Diversion Core API
 * Definition of the Core API used to access low-level functionality of Diversion
 *
 * OpenAPI spec version: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "OpenAPIBaseModel.h"

namespace CoreAPI
{

/*
 * OpenAPISrcHandlersv2WorkspaceCommitWorkspace400Response
 *
 * 
 */
class COREAPI_API OpenAPISrcHandlersv2WorkspaceCommitWorkspace400Response : public Model
{
public:
    virtual ~OpenAPISrcHandlersv2WorkspaceCommitWorkspace400Response() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	/* HTTP status code */
	int32 Status = 0;
	FString Detail;
	TOptional<FString> Title;
	TOptional<FString> Type;
	/* A list of paths that were not found/failed to commit */
	TOptional<TArray<FString>> FailedPaths;
};

}
