// Copyright 2024 Diversion Company, Inc. All Rights Reserved.
/**
 * Diversion Core API
 * Definition of the Core API used to access low-level functionality of Diversion
 *
 * OpenAPI spec version: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "OpenAPIBaseModel.h"

namespace CoreAPI
{

/*
 * OpenAPICreateShelf
 *
 * 
 */
class COREAPI_API OpenAPICreateShelf : public Model
{
public:
    virtual ~OpenAPICreateShelf() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	/* Display name of the shelf */
	FString Name;
	/* Workspace ID from which to shelve changes */
	FString WorkspaceId;
	/* Should reset workspace changes after creating the shelf */
	TOptional<bool> ResetWorkspace;
};

}
