// Copyright 2024 Diversion Company, Inc. All Rights Reserved.
/**
 * Diversion Core API
 * Definition of the Core API used to access low-level functionality of Diversion
 *
 * OpenAPI spec version: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "OpenAPIBaseModel.h"
#include "OpenAPIFileHistoryEntry.h"

namespace CoreAPI
{

/*
 * OpenAPISrcHandlersv2CommitGetObjectHistory200Response
 *
 * 
 */
class COREAPI_API OpenAPISrcHandlersv2CommitGetObjectHistory200Response : public Model
{
public:
    virtual ~OpenAPISrcHandlersv2CommitGetObjectHistory200Response() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	TArray<OpenAPIFileHistoryEntry> Entries;
};

}
