// Copyright 2024 Diversion Company, Inc. All Rights Reserved.
/**
 * Diversion Core API
 * Definition of the Core API used to access low-level functionality of Diversion
 *
 * OpenAPI spec version: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "OpenAPIBaseModel.h"
#include "OpenAPIWorkspaceStatusItems.h"

namespace CoreAPI
{

/*
 * OpenAPIWorkspaceStatus
 *
 * The status of the workspace, meaning its bill of changes. It will contain the total number of changed items and specifically changed files. If paths details were requested, it will also contain an object having &#39;new&#39;, &#39;modified&#39;, &#39;deleted&#39; arrays of file entries, sorted lexicographically. 
 */
class COREAPI_API OpenAPIWorkspaceStatus : public Model
{
public:
    virtual ~OpenAPIWorkspaceStatus() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	/* Number of changed items of all types */
	double ChangedItemsCount;
	/* Number of changed files */
	double ChangedFilesCount;
	/* The result list was trimmed and the counts are a lower bound only */
	TOptional<bool> IncompleteResult;
	TOptional<OpenAPIWorkspaceStatusItems> Items;
	/* List of conflicted file paths, compared to the base branch, if applicable */
	TOptional<TArray<FString>> Conflicts;
};

}
