// Copyright 2024 Diversion Company, Inc. All Rights Reserved.
/**
 * Diversion Core API
 * Definition of the Core API used to access low-level functionality of Diversion
 *
 * OpenAPI spec version: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "OpenAPIBaseModel.h"
#include "OpenAPISupportApi.h"

#include "OpenAPIErrorReport.h"
#include "OpenAPIPresignedUploadUrl.h"

namespace CoreAPI
{

/* Send an error report

*/
class COREAPI_API OpenAPISupportApi::SrcHandlersSupportErrorReportRequest : public Request
{
public:
    virtual ~SrcHandlersSupportErrorReportRequest() {}
	void SetupHttpRequest(const FHttpRequestRef& HttpRequest) const final;
	FString ComputePath() const final;

	OpenAPIErrorReport OpenAPIErrorReport;
};

class COREAPI_API OpenAPISupportApi::SrcHandlersSupportErrorReportResponse : public Response
{
public:
    virtual ~SrcHandlersSupportErrorReportResponse() {}
	void SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode) final;
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;

    
};

/* Get a presigned url that will be used to upload a support bundle

*/
class COREAPI_API OpenAPISupportApi::SrcHandlersSupportGetSupportBundleUploadLinkRequest : public Request
{
public:
    virtual ~SrcHandlersSupportGetSupportBundleUploadLinkRequest() {}
	void SetupHttpRequest(const FHttpRequestRef& HttpRequest) const final;
	FString ComputePath() const final;

	/* The repo ID of the repository */
	TOptional<FString> RepoId;
	/* A description of the support issue */
	TOptional<FString> Message;
	/* The urgency level of the support issue */
	TOptional<int32> Urgency;
};

class COREAPI_API OpenAPISupportApi::SrcHandlersSupportGetSupportBundleUploadLinkResponse : public Response
{
public:
    virtual ~SrcHandlersSupportGetSupportBundleUploadLinkResponse() {}
	void SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode) final;
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;

    OpenAPIPresignedUploadUrl Content;
};

}
