// Copyright 2024 Diversion Company, Inc. All Rights Reserved.
/**
 * Diversion Core API
 * Definition of the Core API used to access low-level functionality of Diversion
 *
 * OpenAPI spec version: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "OpenAPIBaseModel.h"
#include "OpenAPIClientUpdateResult.h"

namespace CoreAPI
{

/*
 * OpenAPIClientUpdateResults
 *
 * A list of update results returned to the client
 */
class COREAPI_API OpenAPIClientUpdateResults : public Model
{
public:
    virtual ~OpenAPIClientUpdateResults() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	TArray<OpenAPIClientUpdateResult> Results;
};

}
