// Copyright 2024 Diversion Company, Inc. All Rights Reserved.
/**
 * Diversion Core API
 * Definition of the Core API used to access low-level functionality of Diversion
 *
 * OpenAPI spec version: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "OpenAPIBaseModel.h"

namespace CoreAPI
{

/*
 * OpenAPIUser
 *
 * User details
 */
class COREAPI_API OpenAPIUser : public Model
{
public:
    virtual ~OpenAPIUser() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	/* URL of the user image */
	TOptional<FString> Image;
	TOptional<FString> Email;
	TOptional<FString> FullName;
	FString Id;
	TOptional<FString> Name;
};

}
