// Copyright 2024 Diversion Company, Inc. All Rights Reserved.
/**
 * Diversion Core API
 * Definition of the Core API used to access low-level functionality of Diversion
 *
 * OpenAPI spec version: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "OpenAPIBaseModel.h"
#include "OpenAPIFileEntry.h"

namespace CoreAPI
{

/*
 * OpenAPIJournalEntry
 *
 * 
 */
class COREAPI_API OpenAPIJournalEntry : public Model
{
public:
    virtual ~OpenAPIJournalEntry() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	OpenAPIFileEntry Entry;
	/* An ordinal ID of a workspace journal entry */
	int32 OrdinalId = 0;
};

}
