// Copyright 2024 Diversion Company, Inc. All Rights Reserved.
/**
 * Diversion Core API
 * Definition of the Core API used to access low-level functionality of Diversion
 *
 * OpenAPI spec version: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "OpenAPIBaseModel.h"

namespace CoreAPI
{

/*
 * OpenAPISrcHandlersv2RepoPostRequest
 *
 * 
 */
class COREAPI_API OpenAPISrcHandlersv2RepoPostRequest : public Model
{
public:
    virtual ~OpenAPISrcHandlersv2RepoPostRequest() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	FString RepoName;
	TOptional<FString> Description;
	TOptional<bool> Branchless;
	TOptional<bool> UseExistingDvignore;
};

}
