// Copyright 2024 Diversion Company, Inc. All Rights Reserved.
/**
 * Diversion Core API
 * Definition of the Core API used to access low-level functionality of Diversion
 *
 * OpenAPI spec version: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "OpenAPIBaseModel.h"

namespace CoreAPI
{

/*
 * OpenAPICommitRequest
 *
 * 
 */
class COREAPI_API OpenAPICommitRequest : public Model
{
public:
    virtual ~OpenAPICommitRequest() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	FString CommitMessage;
	/* Inclusion list of paths to include in the operation. If null, all paths will be included. */
	TOptional<TArray<FString>> IncludePaths;
};

}
