// Copyright 2024 Diversion Company, Inc. All Rights Reserved.
/**
 * Diversion Core API
 * Definition of the Core API used to access low-level functionality of Diversion
 *
 * OpenAPI spec version: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "OpenAPIBaseModel.h"

namespace CoreAPI
{

/*
 * OpenAPICustomRedirectResponse
 *
 * A redirect that needs to be followed in a different HTTP context than the original request.
 */
class COREAPI_API OpenAPICustomRedirectResponse : public Model
{
public:
    virtual ~OpenAPICustomRedirectResponse() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	FString ResultUrl;
	int32 TimeoutSec = 0;
};

}
