// Copyright 2024 Diversion Company, Inc. All Rights Reserved.
/**
 * Diversion Core API
 * Definition of the Core API used to access low-level functionality of Diversion
 *
 * OpenAPI spec version: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "CoreMinimal.h"
#include "OpenAPIBaseModel.h"

namespace CoreAPI
{

class COREAPI_API OpenAPIRepositoryManagementApi : public TSharedFromThis<OpenAPIRepositoryManagementApi>
{
public:
	OpenAPIRepositoryManagementApi();
	~OpenAPIRepositoryManagementApi();

	/* Sets the URL Endpoint.
	* Note: several fallback endpoints can be configured in request retry policies, see Request::SetShouldRetry */
	void SetURL(const FString& Url);

	/* Adds global header params to all requests */
	void AddHeaderParam(const FString& Key, const FString& Value);
	void ClearHeaderParams();

	/* Sets the retry manager to the user-defined retry manager. User must manage the lifetime of the retry manager.
	* If no retry manager is specified and a request needs retries, a default retry manager will be used.
	* See also: Request::SetShouldRetry */
	void SetHttpRetryManager(FHttpRetrySystem::FManager& RetryManager);
	FHttpRetrySystem::FManager& GetHttpRetryManager();

	class SrcHandlersv2RepoListAllRequest;
	class SrcHandlersv2RepoListAllResponse;
	class SrcHandlersv2RepoPostRequest;
	class SrcHandlersv2RepoPostResponse;
	
    DECLARE_DELEGATE_OneParam(FSrcHandlersv2RepoListAllDelegate, const SrcHandlersv2RepoListAllResponse&);
    DECLARE_DELEGATE_OneParam(FSrcHandlersv2RepoPostDelegate, const SrcHandlersv2RepoPostResponse&);
    
    FHttpRequestPtr SrcHandlersv2RepoListAll(const SrcHandlersv2RepoListAllRequest& Request, const FSrcHandlersv2RepoListAllDelegate& Delegate = FSrcHandlersv2RepoListAllDelegate(), float InTimeoutSecs = -1.f) const;
    FHttpRequestPtr SrcHandlersv2RepoPost(const SrcHandlersv2RepoPostRequest& Request, const FSrcHandlersv2RepoPostDelegate& Delegate = FSrcHandlersv2RepoPostDelegate(), float InTimeoutSecs = -1.f) const;
    
private:
    void OnSrcHandlersv2RepoListAllResponse(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FSrcHandlersv2RepoListAllDelegate Delegate) const;
    void OnSrcHandlersv2RepoPostResponse(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FSrcHandlersv2RepoPostDelegate Delegate) const;
    
	FHttpRequestRef CreateHttpRequest(const Request& Request) const;
	bool IsValid() const;
	void HandleResponse(FHttpResponsePtr HttpResponse, bool bSucceeded, Response& InOutResponse) const;

	FString Url;
	TMap<FString,FString> AdditionalHeaderParams;
	mutable FHttpRetrySystem::FManager* RetryManager = nullptr;
	mutable TUniquePtr<HttpRetryManager> DefaultRetryManager;
};

}
