// Copyright 2024 Diversion Company, Inc. All Rights Reserved.
/**
 * Diversion Core API
 * Definition of the Core API used to access low-level functionality of Diversion
 *
 * OpenAPI spec version: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "CoreMinimal.h"
#include "OpenAPIBaseModel.h"

namespace CoreAPI
{

class COREAPI_API OpenAPIAnalyticsApi : public TSharedFromThis<OpenAPIAnalyticsApi>
{
public:
	OpenAPIAnalyticsApi();
	~OpenAPIAnalyticsApi();

	/* Sets the URL Endpoint.
	* Note: several fallback endpoints can be configured in request retry policies, see Request::SetShouldRetry */
	void SetURL(const FString& Url);

	/* Adds global header params to all requests */
	void AddHeaderParam(const FString& Key, const FString& Value);
	void ClearHeaderParams();

	/* Sets the retry manager to the user-defined retry manager. User must manage the lifetime of the retry manager.
	* If no retry manager is specified and a request needs retries, a default retry manager will be used.
	* See also: Request::SetShouldRetry */
	void SetHttpRetryManager(FHttpRetrySystem::FManager& RetryManager);
	FHttpRetrySystem::FManager& GetHttpRetryManager();

	class SrcHandlersAnalyticsIdentifyRequest;
	class SrcHandlersAnalyticsIdentifyResponse;
	class SrcHandlersAnalyticsIngestRequest;
	class SrcHandlersAnalyticsIngestResponse;
	class SrcHandlersAnalyticsIngestAnonRequest;
	class SrcHandlersAnalyticsIngestAnonResponse;
	
    DECLARE_DELEGATE_OneParam(FSrcHandlersAnalyticsIdentifyDelegate, const SrcHandlersAnalyticsIdentifyResponse&);
    DECLARE_DELEGATE_OneParam(FSrcHandlersAnalyticsIngestDelegate, const SrcHandlersAnalyticsIngestResponse&);
    DECLARE_DELEGATE_OneParam(FSrcHandlersAnalyticsIngestAnonDelegate, const SrcHandlersAnalyticsIngestAnonResponse&);
    
    FHttpRequestPtr SrcHandlersAnalyticsIdentify(const SrcHandlersAnalyticsIdentifyRequest& Request, const FSrcHandlersAnalyticsIdentifyDelegate& Delegate = FSrcHandlersAnalyticsIdentifyDelegate(), float InTimeoutSecs = -1.f) const;
    FHttpRequestPtr SrcHandlersAnalyticsIngest(const SrcHandlersAnalyticsIngestRequest& Request, const FSrcHandlersAnalyticsIngestDelegate& Delegate = FSrcHandlersAnalyticsIngestDelegate(), float InTimeoutSecs = -1.f) const;
    FHttpRequestPtr SrcHandlersAnalyticsIngestAnon(const SrcHandlersAnalyticsIngestAnonRequest& Request, const FSrcHandlersAnalyticsIngestAnonDelegate& Delegate = FSrcHandlersAnalyticsIngestAnonDelegate(), float InTimeoutSecs = -1.f) const;
    
private:
    void OnSrcHandlersAnalyticsIdentifyResponse(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FSrcHandlersAnalyticsIdentifyDelegate Delegate) const;
    void OnSrcHandlersAnalyticsIngestResponse(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FSrcHandlersAnalyticsIngestDelegate Delegate) const;
    void OnSrcHandlersAnalyticsIngestAnonResponse(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FSrcHandlersAnalyticsIngestAnonDelegate Delegate) const;
    
	FHttpRequestRef CreateHttpRequest(const Request& Request) const;
	bool IsValid() const;
	void HandleResponse(FHttpResponsePtr HttpResponse, bool bSucceeded, Response& InOutResponse) const;

	FString Url;
	TMap<FString,FString> AdditionalHeaderParams;
	mutable FHttpRetrySystem::FManager* RetryManager = nullptr;
	mutable TUniquePtr<HttpRetryManager> DefaultRetryManager;
};

}
