// Copyright 2024 Diversion Company, Inc. All Rights Reserved.
/**
 * Diversion Core API
 * Definition of the Core API used to access low-level functionality of Diversion
 *
 * OpenAPI spec version: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "OpenAPIBaseModel.h"
#include "OpenAPIDebugApi.h"


namespace CoreAPI
{

/* Check server is alive

*/
class COREAPI_API OpenAPIDebugApi::SrcHandlersDebugIsAliveRequest : public Request
{
public:
    virtual ~SrcHandlersDebugIsAliveRequest() {}
	void SetupHttpRequest(const FHttpRequestRef& HttpRequest) const final;
	FString ComputePath() const final;

};

class COREAPI_API OpenAPIDebugApi::SrcHandlersDebugIsAliveResponse : public Response
{
public:
    virtual ~SrcHandlersDebugIsAliveResponse() {}
	void SetHttpResponseCode(EHttpResponseCodes::Type InHttpResponseCode) final;
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;

    
};

}
