// Copyright 2024 Diversion Company, Inc. All Rights Reserved.
/**
 * Diversion Core API
 * Definition of the Core API used to access low-level functionality of Diversion
 *
 * OpenAPI spec version: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "OpenAPIBaseModel.h"
#include "OpenAPIUser.h"

namespace CoreAPI
{

/*
 * OpenAPIRefFileStatus
 *
 * Changes on some file in some ref
 */
class COREAPI_API OpenAPIRefFileStatus : public Model
{
public:
    virtual ~OpenAPIRefFileStatus() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	/* ID of the workspace, if applicable */
	TOptional<FString> WorkspaceId;
	/* ID of the commit the ref is based on */
	FString CommitId;
	/* ID of the branch or of the branch on which the workspace is based on, if applicable */
	TOptional<FString> BranchId;
	/* Name of the branch, if applicable */
	TOptional<FString> BranchName;
	int32 Status = 0;
	OpenAPIUser Author;
	/* Seconds since epoch UTC */
	TOptional<int64> Mtime;
};

}
