// Copyright 2024 Diversion Company, Inc. All Rights Reserved.
/**
 * Diversion Core API
 * Definition of the Core API used to access low-level functionality of Diversion
 *
 * OpenAPI spec version: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "OpenAPIBaseModel.h"

namespace CoreAPI
{

/*
 * OpenAPIAsyncResponse
 *
 * Response with the location of the result of an asynchronous processing of the request
 */
class COREAPI_API OpenAPIAsyncResponse : public Model
{
public:
    virtual ~OpenAPIAsyncResponse() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	FString ResultUrl;
	int32 TimeoutSec = 0;
	int32 Status = 0;
	FString RefId;
	TOptional<int32> PollIntervalSec;
};

}
