// Copyright 2024 Diversion Company, Inc. All Rights Reserved.
/**
 * Diversion Core API
 * Definition of the Core API used to access low-level functionality of Diversion
 *
 * The version of the OpenAPI document: 0.2.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.10.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * RefsFileStatus.h
 *
 * Status of a file in multiple refs
 */
#pragma once


#include "ModelBase.h"
#include "RefFileStatus.h"

namespace Diversion {
namespace CoreAPI {
namespace Model {

class RefFileStatus;

/*
 * RefsFileStatus
 *
 * Status of a file in multiple refs
 */
class COREAPI_API RefsFileStatus
    : public Model
{
public:
    virtual ~RefsFileStatus() {}

	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) override;
	void WriteJson(JsonWriter& Writer) const override;


	/* File path */
	FString mPath;

	/* Details of changes of the file per relevant workspace */
	TArray<RefFileStatus> mFile_statuses;

};


}
}
}

