// Copyright 2024 Diversion Company, Inc. All Rights Reserved.
/**
 * Diversion Core API
 * Definition of the Core API used to access low-level functionality of Diversion
 *
 * The version of the OpenAPI document: 0.2.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.10.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * ResetStatus.h
 *
 * Response of a reset command.
 */
#pragma once


#include "ModelBase.h"

namespace Diversion {
namespace CoreAPI {
namespace Model {


/*
 * ResetStatus
 *
 * Response of a reset command.
 */
class COREAPI_API ResetStatus
    : public Model
{
public:
    virtual ~ResetStatus() {}

	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) override;
	void WriteJson(JsonWriter& Writer) const override;


	/* Paths that were successfully reset. */
	TArray<FString> mSuccess;

	/* Paths that were not found. */
	TArray<FString> mFail;

	/* Paths that were not reset. */
	TArray<FString> mSkipped;

};


}
}
}

