// Copyright 2024 Diversion Company, Inc. All Rights Reserved.
/**
 * Diversion Core API
 * Definition of the Core API used to access low-level functionality of Diversion
 *
 * The version of the OpenAPI document: 0.2.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.10.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * Src_handlersv2_repo_list_all_200_response.h
 *
 * 
 */
#pragma once


#include "ModelBase.h"
#include "Repo.h"

namespace Diversion {
namespace CoreAPI {
namespace Model {

class Repo;

/*
 * Src_handlersv2_repo_list_all_200_response
 *
 * 
 */
class COREAPI_API Src_handlersv2_repo_list_all_200_response
    : public Model
{
public:
    virtual ~Src_handlersv2_repo_list_all_200_response() {}

	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) override;
	void WriteJson(JsonWriter& Writer) const override;


	enum class ObjectEnum
	{
		REPO,
  	};

	static FString EnumToString(const ObjectEnum& EnumValue);
	static bool EnumFromString(const FString& EnumAsString, ObjectEnum& EnumValue);
	ObjectEnum mobject;

	TArray<Repo> mItems;

};


}
}
}

