// Copyright 2024 Diversion Company, Inc. All Rights Reserved.
/**
 * Diversion Core API
 * Definition of the Core API used to access low-level functionality of Diversion
 *
 * The version of the OpenAPI document: 0.2.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.10.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * WorkspaceRename.h
 *
 * Properties to modify in an existing workspace
 */
#pragma once


#include "ModelBase.h"

namespace Diversion {
namespace CoreAPI {
namespace Model {


/*
 * WorkspaceRename
 *
 * Properties to modify in an existing workspace
 */
class COREAPI_API WorkspaceRename
    : public Model
{
public:
    virtual ~WorkspaceRename() {}

	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) override;
	void WriteJson(JsonWriter& Writer) const override;


	/* A name to set for the workspace */
	FString mName;

};


}
}
}

