// Copyright 2024 Diversion Company, Inc. All Rights Reserved.
/**
 * Diversion Core API
 * Definition of the Core API used to access low-level functionality of Diversion
 *
 * The version of the OpenAPI document: 0.2.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.10.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * WorkspaceCheckout.h
 *
 * Properties to modify in an existing workspace
 */
#pragma once


#include "ModelBase.h"

namespace Diversion {
namespace CoreAPI {
namespace Model {


/*
 * WorkspaceCheckout
 *
 * Properties to modify in an existing workspace
 */
class COREAPI_API WorkspaceCheckout
    : public Model
{
public:
    virtual ~WorkspaceCheckout() {}

	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) override;
	void WriteJson(JsonWriter& Writer) const override;


	/* A branch or commit ID to point the workspace onto */
	FString mRef_id;

};


}
}
}

