// Copyright 2024 Diversion Company, Inc. All Rights Reserved.
/**
 * Agent API
 * API of Diversion sync agent
 *
 * The version of the OpenAPI document: 1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.10.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * CloneRepo.h
 *
 * 
 */
#pragma once


#include "ModelBase.h"
#include "Reference.h"

namespace Diversion {
namespace AgentAPI {
namespace Model {

class Reference;

/*
 * CloneRepo
 *
 * 
 */
class AGENTAPI_API CloneRepo
    : public Model
{
public:
    virtual ~CloneRepo() {}

	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) override;
	void WriteJson(JsonWriter& Writer) const override;


	FString mPath;

	TOptional<FString> mWorkspaceID;

	TOptional<bool> mOverridePath;

	TOptional<Reference> mRef;

};


}
}
}

