// Copyright 2024 Diversion Company, Inc. All Rights Reserved.
/**
 * Agent API
 * API of Diversion sync agent
 *
 * The version of the OpenAPI document: 1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.10.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * FileStatusAggregation.h
 *
 * 
 */
#pragma once


#include "ModelBase.h"
#include "ProgressStatus.h"

namespace Diversion {
namespace AgentAPI {
namespace Model {

class ProgressStatus;

/*
 * FileStatusAggregation
 *
 * 
 */
class AGENTAPI_API FileStatusAggregation
    : public Model
{
public:
    virtual ~FileStatusAggregation() {}

	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) override;
	void WriteJson(JsonWriter& Writer) const override;


	int32_t mItemsCount = 0;

	ProgressStatus mProgressStatus;

};


}
}
}

