// Copyright 2024 Diversion Company, Inc. All Rights Reserved.
/**
 * Agent API
 * API of Diversion sync agent
 *
 * The version of the OpenAPI document: 1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.10.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * IsAlive_200_response.h
 *
 * 
 */
#pragma once


#include "ModelBase.h"

namespace Diversion {
namespace AgentAPI {
namespace Model {


/*
 * IsAlive_200_response
 *
 * 
 */
class AGENTAPI_API IsAlive_200_response
    : public Model
{
public:
    virtual ~IsAlive_200_response() {}

	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) override;
	void WriteJson(JsonWriter& Writer) const override;


	TOptional<FString> mVersion;

};


}
}
}

