// Copyright 2024 Diversion Company, Inc. All Rights Reserved.
/**
 * Agent API
 * API of Diversion sync agent
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "OpenAPIBaseModel.h"

namespace AgentAPI
{

/*
 * OpenAPISupportBundle
 *
 * 
 */
class AGENTAPI_API OpenAPISupportBundle : public Model
{
public:
    virtual ~OpenAPISupportBundle() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	TOptional<FString> RepoID;
	FString Message;
	enum class UrgencyLevelEnum
	{
		_0,
		_1,
		_2,
		_3,
		_4,
  	};

	static FString EnumToString(const UrgencyLevelEnum& EnumValue);
	static bool EnumFromString(const FString& EnumAsString, UrgencyLevelEnum& EnumValue);
	/* The urgency level of the issue; 0 - Not Set, 1- Low, 2 - Normal, 3 - High, 4 - Urgent */
	TOptional<UrgencyLevelEnum> UrgencyLevel;
};

}
