// Copyright 2024 Diversion Company, Inc. All Rights Reserved.
/**
 * Agent API
 * API of Diversion sync agent
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "OpenAPIBaseModel.h"

namespace AgentAPI
{

/*
 * OpenAPIWorkspaceConfiguration
 *
 * 
 */
class AGENTAPI_API OpenAPIWorkspaceConfiguration : public Model
{
public:
    virtual ~OpenAPIWorkspaceConfiguration() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	FString WorkspaceID;
	FString RepoID;
	FString Path;
	FString AccountID;
	TOptional<FString> BranchID;
	TOptional<FString> BranchName;
	FString CommitID;
	bool Paused = false;
	bool ShouldDownload = false;
	TOptional<int32> MaxConcurrentWrites;
	TOptional<FString> RepoName;
};

}
