// Copyright 2024 Diversion Company, Inc. All Rights Reserved.
/**
 * Agent API
 * API of Diversion sync agent
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "OpenAPIBaseModel.h"

namespace AgentAPI
{

/*
 * OpenAPIWorkspaceSyncProgressErrorPathsInner
 *
 * 
 */
class AGENTAPI_API OpenAPIWorkspaceSyncProgressErrorPathsInner : public Model
{
public:
    virtual ~OpenAPIWorkspaceSyncProgressErrorPathsInner() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	TOptional<FString> Path;
	/* Diversion Error code for the path */
	TOptional<int32> ErrorCode;
	TOptional<FString> ErrorString;
};

}
