// Copyright 2024 Diversion Company, Inc. All Rights Reserved.
/**
 * Agent API
 * API of Diversion sync agent
 *
 * The version of the OpenAPI document: 1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.10.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * WorkspaceSyncProgress.h
 *
 * 
 */
#pragma once


#include "ModelBase.h"
#include "WorkspaceSyncProgress_ErrorPaths_inner.h"
#include "WorkspaceSyncProgress_FileStats.h"
#include <vector>

namespace Diversion {
namespace AgentAPI {
namespace Model {

class WorkspaceSyncProgress_FileStats;
class WorkspaceSyncProgress_ErrorPaths_inner;

/*
 * WorkspaceSyncProgress
 *
 * 
 */
class AGENTAPI_API WorkspaceSyncProgress
    : public Model
{
public:
    virtual ~WorkspaceSyncProgress() {}

	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) override;
	void WriteJson(JsonWriter& Writer) const override;


	FString mWorkspaceID;

	WorkspaceSyncProgress_FileStats mFileStats;

	TOptional<int32_t> mLocalEventQueueSize;

	TOptional<FString> mCurrentSyncAction;

	TOptional<FString> mLastErr;

	TOptional<bool> mEnableLockRelease;

	TOptional<TArray<WorkspaceSyncProgress_ErrorPaths_inner>> mErrorPaths;

	TOptional<FString> mBlobTransferStatus;

	TOptional<bool> mIsPaused;

};


}
}
}

