// Copyright 2024 Diversion Company, Inc. All Rights Reserved.
/**
 * Agent API
 * API of Diversion sync agent
 *
 * The version of the OpenAPI document: 1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.10.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * WorkspaceConfiguration.h
 *
 * 
 */
#pragma once


#include "ModelBase.h"

namespace Diversion {
namespace AgentAPI {
namespace Model {


/*
 * WorkspaceConfiguration
 *
 * 
 */
class AGENTAPI_API WorkspaceConfiguration
    : public Model
{
public:
    virtual ~WorkspaceConfiguration() {}

	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) override;
	void WriteJson(JsonWriter& Writer) const override;


	FString mWorkspaceID;

	FString mRepoID;

	FString mPath;

	FString mAccountID;

	TOptional<FString> mBranchID;

	TOptional<FString> mBranchName;

	FString mCommitID;

	bool mPaused = false;

	bool mShouldDownload = false;

	TOptional<int32_t> mMaxConcurrentWrites;

	TOptional<FString> mRepoName;

};


}
}
}

