// Copyright 2024 Diversion Company, Inc. All Rights Reserved.
/**
 * Agent API
 * API of Diversion sync agent
 *
 * The version of the OpenAPI document: 1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.10.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * WorkspaceSyncProgress_ErrorPaths_inner.h
 *
 * 
 */
#pragma once


#include "ModelBase.h"

namespace Diversion {
namespace AgentAPI {
namespace Model {


/*
 * WorkspaceSyncProgress_ErrorPaths_inner
 *
 * 
 */
class AGENTAPI_API WorkspaceSyncProgress_ErrorPaths_inner
    : public Model
{
public:
    virtual ~WorkspaceSyncProgress_ErrorPaths_inner() {}

	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) override;
	void WriteJson(JsonWriter& Writer) const override;


	TOptional<FString> mPath;

	/* Diversion Error code for the path */
	TOptional<int32_t> mErrorCode;

	TOptional<FString> mErrorString;

};


}
}
}

