// Copyright 2024 Diversion Company, Inc. All Rights Reserved.
/**
 * Agent API
 * API of Diversion sync agent
 *
 * The version of the OpenAPI document: 1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.10.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "JsonBody.h"
#include "CloneRepo.h"

namespace Diversion {
namespace AgentAPI {
namespace Model {



void CloneRepo::WriteJson(JsonWriter& Writer) const
{
	Writer->WriteObjectStart();
	Writer->WriteIdentifierPrefix(TEXT("Path")); WriteJsonValue(Writer, mPath);
	if (mWorkspaceID.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("WorkspaceID")); WriteJsonValue(Writer, mWorkspaceID.GetValue());
	}
	if (mOverridePath.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("OverridePath")); WriteJsonValue(Writer, mOverridePath.GetValue());
	}
	if (mRef.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("Ref")); WriteJsonValue(Writer, mRef.GetValue());
	}
	Writer->WriteObjectEnd();
}

bool CloneRepo::FromJson(const TSharedPtr<FJsonValue>& JsonValue)
{

	const TSharedPtr<FJsonObject>* InnerGeneratorOpenAPIObject;
	if (!JsonValue->TryGetObject(InnerGeneratorOpenAPIObject))
		return false;

	bool ParseSuccess = true;

    

	ParseSuccess &= TryGetJsonValue(*InnerGeneratorOpenAPIObject, TEXT("Path"), mPath);
    ParseSuccess &= TryGetJsonValue(*InnerGeneratorOpenAPIObject, TEXT("WorkspaceID"), mWorkspaceID);
    ParseSuccess &= TryGetJsonValue(*InnerGeneratorOpenAPIObject, TEXT("OverridePath"), mOverridePath);
    ParseSuccess &= TryGetJsonValue(*InnerGeneratorOpenAPIObject, TEXT("Ref"), mRef);


	return ParseSuccess;
}


}
}
}

