// Copyright 2024 Diversion Company, Inc. All Rights Reserved.
/**
 * Agent API
 * API of Diversion sync agent
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#include "OpenAPIWorkspaceSyncProgressFileStats.h"

#include "AgentAPIModule.h"
#include "OpenAPIHelpers.h"

#include "Templates/SharedPointer.h"

namespace AgentAPI
{

void OpenAPIWorkspaceSyncProgressFileStats::WriteJson(JsonWriter& Writer) const
{
	Writer->WriteObjectStart();
	if (Inbound.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("Inbound")); WriteJsonValue(Writer, Inbound.GetValue());
	}
	if (Outbound.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("Outbound")); WriteJsonValue(Writer, Outbound.GetValue());
	}
	Writer->WriteObjectEnd();
}

bool OpenAPIWorkspaceSyncProgressFileStats::FromJson(const TSharedPtr<FJsonValue>& JsonValue)
{
	const TSharedPtr<FJsonObject>* InnerGeneratorOpenAPIObject;
	if (!JsonValue->TryGetObject(InnerGeneratorOpenAPIObject))
		return false;

	bool ParseSuccess = true;

	ParseSuccess &= TryGetJsonValue(*InnerGeneratorOpenAPIObject, TEXT("Inbound"), Inbound);
	ParseSuccess &= TryGetJsonValue(*InnerGeneratorOpenAPIObject, TEXT("Outbound"), Outbound);

	return ParseSuccess;
}

}
