// Copyright 2024 Diversion Company, Inc. All Rights Reserved.
/**
 * Agent API
 * API of Diversion sync agent
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#include "OpenAPIWorkspaceSyncProgress.h"

#include "AgentAPIModule.h"
#include "OpenAPIHelpers.h"

#include "Templates/SharedPointer.h"

namespace AgentAPI
{

void OpenAPIWorkspaceSyncProgress::WriteJson(JsonWriter& Writer) const
{
	Writer->WriteObjectStart();
	Writer->WriteIdentifierPrefix(TEXT("WorkspaceID")); WriteJsonValue(Writer, WorkspaceID);
	Writer->WriteIdentifierPrefix(TEXT("FileStats")); WriteJsonValue(Writer, FileStats);
	if (LocalEventQueueSize.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("LocalEventQueueSize")); WriteJsonValue(Writer, LocalEventQueueSize.GetValue());
	}
	if (CurrentSyncAction.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("CurrentSyncAction")); WriteJsonValue(Writer, CurrentSyncAction.GetValue());
	}
	if (LastErr.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("LastErr")); WriteJsonValue(Writer, LastErr.GetValue());
	}
	if (EnableLockRelease.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("EnableLockRelease")); WriteJsonValue(Writer, EnableLockRelease.GetValue());
	}
	if (ErrorPaths.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("ErrorPaths")); WriteJsonValue(Writer, ErrorPaths.GetValue());
	}
	if (BlobTransferStatus.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("BlobTransferStatus")); WriteJsonValue(Writer, BlobTransferStatus.GetValue());
	}
	if (IsPaused.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("IsPaused")); WriteJsonValue(Writer, IsPaused.GetValue());
	}
	Writer->WriteObjectEnd();
}

bool OpenAPIWorkspaceSyncProgress::FromJson(const TSharedPtr<FJsonValue>& JsonValue)
{
	const TSharedPtr<FJsonObject>* InnerGeneratorOpenAPIObject;
	if (!JsonValue->TryGetObject(InnerGeneratorOpenAPIObject))
		return false;

	bool ParseSuccess = true;

	ParseSuccess &= TryGetJsonValue(*InnerGeneratorOpenAPIObject, TEXT("WorkspaceID"), WorkspaceID);
	ParseSuccess &= TryGetJsonValue(*InnerGeneratorOpenAPIObject, TEXT("FileStats"), FileStats);
	ParseSuccess &= TryGetJsonValue(*InnerGeneratorOpenAPIObject, TEXT("LocalEventQueueSize"), LocalEventQueueSize);
	ParseSuccess &= TryGetJsonValue(*InnerGeneratorOpenAPIObject, TEXT("CurrentSyncAction"), CurrentSyncAction);
	ParseSuccess &= TryGetJsonValue(*InnerGeneratorOpenAPIObject, TEXT("LastErr"), LastErr);
	ParseSuccess &= TryGetJsonValue(*InnerGeneratorOpenAPIObject, TEXT("EnableLockRelease"), EnableLockRelease);
	ParseSuccess &= TryGetJsonValue(*InnerGeneratorOpenAPIObject, TEXT("ErrorPaths"), ErrorPaths);
	ParseSuccess &= TryGetJsonValue(*InnerGeneratorOpenAPIObject, TEXT("BlobTransferStatus"), BlobTransferStatus);
	ParseSuccess &= TryGetJsonValue(*InnerGeneratorOpenAPIObject, TEXT("IsPaused"), IsPaused);

	return ParseSuccess;
}

}
