// Copyright 2024 Diversion Company, Inc. All Rights Reserved.
/**
 * Agent API
 * API of Diversion sync agent
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#include "OpenAPIOpenLocalWorkspaceRequest.h"

#include "AgentAPIModule.h"
#include "OpenAPIHelpers.h"

#include "Templates/SharedPointer.h"

namespace AgentAPI
{

void OpenAPIOpenLocalWorkspaceRequest::WriteJson(JsonWriter& Writer) const
{
	Writer->WriteObjectStart();
	Writer->WriteIdentifierPrefix(TEXT("workspaceId")); WriteJsonValue(Writer, WorkspaceId);
	if (SubPath.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("subPath")); WriteJsonValue(Writer, SubPath.GetValue());
	}
	if (Selected.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("selected")); WriteJsonValue(Writer, Selected.GetValue());
	}
	Writer->WriteObjectEnd();
}

bool OpenAPIOpenLocalWorkspaceRequest::FromJson(const TSharedPtr<FJsonValue>& JsonValue)
{
	const TSharedPtr<FJsonObject>* InnerGeneratorOpenAPIObject;
	if (!JsonValue->TryGetObject(InnerGeneratorOpenAPIObject))
		return false;

	bool ParseSuccess = true;

	ParseSuccess &= TryGetJsonValue(*InnerGeneratorOpenAPIObject, TEXT("workspaceId"), WorkspaceId);
	ParseSuccess &= TryGetJsonValue(*InnerGeneratorOpenAPIObject, TEXT("subPath"), SubPath);
	ParseSuccess &= TryGetJsonValue(*InnerGeneratorOpenAPIObject, TEXT("selected"), Selected);

	return ParseSuccess;
}

}
