// Copyright 2024 Diversion Company, Inc. All Rights Reserved.
/**
 * Agent API
 * API of Diversion sync agent
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#include "OpenAPIFileStatusAggregation.h"

#include "AgentAPIModule.h"
#include "OpenAPIHelpers.h"

#include "Templates/SharedPointer.h"

namespace AgentAPI
{

void OpenAPIFileStatusAggregation::WriteJson(JsonWriter& Writer) const
{
	Writer->WriteObjectStart();
	Writer->WriteIdentifierPrefix(TEXT("ItemsCount")); WriteJsonValue(Writer, ItemsCount);
	Writer->WriteIdentifierPrefix(TEXT("ProgressStatus")); WriteJsonValue(Writer, ProgressStatus);
	Writer->WriteObjectEnd();
}

bool OpenAPIFileStatusAggregation::FromJson(const TSharedPtr<FJsonValue>& JsonValue)
{
	const TSharedPtr<FJsonObject>* InnerGeneratorOpenAPIObject;
	if (!JsonValue->TryGetObject(InnerGeneratorOpenAPIObject))
		return false;

	bool ParseSuccess = true;

	ParseSuccess &= TryGetJsonValue(*InnerGeneratorOpenAPIObject, TEXT("ItemsCount"), ItemsCount);
	ParseSuccess &= TryGetJsonValue(*InnerGeneratorOpenAPIObject, TEXT("ProgressStatus"), ProgressStatus);

	return ParseSuccess;
}

}
