// Copyright 2024 Diversion Company, Inc. All Rights Reserved.
/**
 * Agent API
 * API of Diversion sync agent
 *
 * The version of the OpenAPI document: 1.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.10.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "JsonBody.h"
#include "WorkspaceSyncProgress_FileStats.h"

namespace Diversion {
namespace AgentAPI {
namespace Model {



void WorkspaceSyncProgress_FileStats::WriteJson(JsonWriter& Writer) const
{
	Writer->WriteObjectStart();
	if (mInbound.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("Inbound")); WriteJsonValue(Writer, mInbound.GetValue());
	}
	if (mOutbound.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("Outbound")); WriteJsonValue(Writer, mOutbound.GetValue());
	}
	Writer->WriteObjectEnd();
}

bool WorkspaceSyncProgress_FileStats::FromJson(const TSharedPtr<FJsonValue>& JsonValue)
{

	const TSharedPtr<FJsonObject>* InnerGeneratorOpenAPIObject;
	if (!JsonValue->TryGetObject(InnerGeneratorOpenAPIObject))
		return false;

	bool ParseSuccess = true;

    

    ParseSuccess &= TryGetJsonValue(*InnerGeneratorOpenAPIObject, TEXT("Inbound"), mInbound);
    ParseSuccess &= TryGetJsonValue(*InnerGeneratorOpenAPIObject, TEXT("Outbound"), mOutbound);


	return ParseSuccess;
}


}
}
}

