// Copyright 2024 Diversion Company, Inc. All Rights Reserved.
/**
 * Diversion Core API
 * Definition of the Core API used to access low-level functionality of Diversion
 *
 * The version of the OpenAPI document: 0.2.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.10.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "JsonBody.h"
#include "BlobLocation.h"

namespace Diversion {
namespace CoreAPI {
namespace Model {



void BlobLocation::WriteJson(JsonWriter& Writer) const
{
	Writer->WriteObjectStart();
	Writer->WriteIdentifierPrefix(TEXT("storage_backend")); WriteJsonValue(Writer, mStorage_backend);
	Writer->WriteIdentifierPrefix(TEXT("storage_uri")); WriteJsonValue(Writer, mStorage_uri);
	Writer->WriteObjectEnd();
}

bool BlobLocation::FromJson(const TSharedPtr<FJsonValue>& JsonValue)
{

	const TSharedPtr<FJsonObject>* InnerGeneratorOpenAPIObject;
	if (!JsonValue->TryGetObject(InnerGeneratorOpenAPIObject))
		return false;

	bool ParseSuccess = true;

    

	ParseSuccess &= TryGetJsonValue(*InnerGeneratorOpenAPIObject, TEXT("storage_backend"), mStorage_backend);
	ParseSuccess &= TryGetJsonValue(*InnerGeneratorOpenAPIObject, TEXT("storage_uri"), mStorage_uri);


	return ParseSuccess;
}


}
}
}

