// Copyright 2024 Diversion Company, Inc. All Rights Reserved.
/**
 * Diversion Core API
 * Definition of the Core API used to access low-level functionality of Diversion
 *
 * The version of the OpenAPI document: 0.2.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.10.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "JsonBody.h"
#include "Commit.h"

namespace Diversion {
namespace CoreAPI {
namespace Model {



void Commit::WriteJson(JsonWriter& Writer) const
{
	Writer->WriteObjectStart();
	Writer->WriteIdentifierPrefix(TEXT("commit_id")); WriteJsonValue(Writer, mCommit_id);
	Writer->WriteIdentifierPrefix(TEXT("created_ts")); WriteJsonValue(Writer, mCreated_ts);
	if (mCommit_message.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("commit_message")); WriteJsonValue(Writer, mCommit_message.GetValue());
	}
	Writer->WriteIdentifierPrefix(TEXT("branch_id")); WriteJsonValue(Writer, mBranch_id);
	Writer->WriteIdentifierPrefix(TEXT("author")); WriteJsonValue(Writer, mAuthor);
	Writer->WriteIdentifierPrefix(TEXT("parents")); WriteJsonValue(Writer, mParents);
	Writer->WriteObjectEnd();
}

bool Commit::FromJson(const TSharedPtr<FJsonValue>& JsonValue)
{

	const TSharedPtr<FJsonObject>* InnerGeneratorOpenAPIObject;
	if (!JsonValue->TryGetObject(InnerGeneratorOpenAPIObject))
		return false;

	bool ParseSuccess = true;

    

	ParseSuccess &= TryGetJsonValue(*InnerGeneratorOpenAPIObject, TEXT("commit_id"), mCommit_id);
	ParseSuccess &= TryGetJsonValue(*InnerGeneratorOpenAPIObject, TEXT("created_ts"), mCreated_ts);
    ParseSuccess &= TryGetJsonValue(*InnerGeneratorOpenAPIObject, TEXT("commit_message"), mCommit_message);
	ParseSuccess &= TryGetJsonValue(*InnerGeneratorOpenAPIObject, TEXT("branch_id"), mBranch_id);
	ParseSuccess &= TryGetJsonValue(*InnerGeneratorOpenAPIObject, TEXT("author"), mAuthor);
	ParseSuccess &= TryGetJsonValue(*InnerGeneratorOpenAPIObject, TEXT("parents"), mParents);


	return ParseSuccess;
}


}
}
}

