// Copyright 2024 Diversion Company, Inc. All Rights Reserved.
/**
 * Diversion Core API
 * Definition of the Core API used to access low-level functionality of Diversion
 *
 * The version of the OpenAPI document: 0.2.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.10.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "JsonBody.h"
#include "ComparisonItem.h"

namespace Diversion {
namespace CoreAPI {
namespace Model {



void ComparisonItem::WriteJson(JsonWriter& Writer) const
{
	Writer->WriteObjectStart();
	if (mBase_item.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("base_item")); WriteJsonValue(Writer, mBase_item.GetValue());
	}
	if (mOther_item.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("other_item")); WriteJsonValue(Writer, mOther_item.GetValue());
	}
	Writer->WriteIdentifierPrefix(TEXT("status")); WriteJsonValue(Writer, mStatus);
	Writer->WriteObjectEnd();
}

bool ComparisonItem::FromJson(const TSharedPtr<FJsonValue>& JsonValue)
{

	const TSharedPtr<FJsonObject>* InnerGeneratorOpenAPIObject;
	if (!JsonValue->TryGetObject(InnerGeneratorOpenAPIObject))
		return false;

	bool ParseSuccess = true;

    

    ParseSuccess &= TryGetJsonValue(*InnerGeneratorOpenAPIObject, TEXT("base_item"), mBase_item);
    ParseSuccess &= TryGetJsonValue(*InnerGeneratorOpenAPIObject, TEXT("other_item"), mOther_item);
	ParseSuccess &= TryGetJsonValue(*InnerGeneratorOpenAPIObject, TEXT("status"), mStatus);


	return ParseSuccess;
}


}
}
}

