// Copyright 2024 Diversion Company, Inc. All Rights Reserved.
/**
 * Diversion Core API
 * Definition of the Core API used to access low-level functionality of Diversion
 *
 * The version of the OpenAPI document: 0.2.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.10.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "JsonBody.h"
#include "CompletedMultipartUpload.h"

namespace Diversion {
namespace CoreAPI {
namespace Model {



void CompletedMultipartUpload::WriteJson(JsonWriter& Writer) const
{
	Writer->WriteObjectStart();
	Writer->WriteIdentifierPrefix(TEXT("sha1")); WriteJsonValue(Writer, mSha1);
	Writer->WriteIdentifierPrefix(TEXT("upload_id")); WriteJsonValue(Writer, mUpload_id);
	Writer->WriteIdentifierPrefix(TEXT("parts")); WriteJsonValue(Writer, mParts);
	Writer->WriteObjectEnd();
}

bool CompletedMultipartUpload::FromJson(const TSharedPtr<FJsonValue>& JsonValue)
{

	const TSharedPtr<FJsonObject>* InnerGeneratorOpenAPIObject;
	if (!JsonValue->TryGetObject(InnerGeneratorOpenAPIObject))
		return false;

	bool ParseSuccess = true;

    

	ParseSuccess &= TryGetJsonValue(*InnerGeneratorOpenAPIObject, TEXT("sha1"), mSha1);
	ParseSuccess &= TryGetJsonValue(*InnerGeneratorOpenAPIObject, TEXT("upload_id"), mUpload_id);
	ParseSuccess &= TryGetJsonValue(*InnerGeneratorOpenAPIObject, TEXT("parts"), mParts);


	return ParseSuccess;
}


}
}
}

