// Copyright 2024 Diversion Company, Inc. All Rights Reserved.
/**
 * Diversion Core API
 * Definition of the Core API used to access low-level functionality of Diversion
 *
 * The version of the OpenAPI document: 0.2.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.10.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "JsonBody.h"
#include "DetailedMerge.h"

namespace Diversion {
namespace CoreAPI {
namespace Model {



void DetailedMerge::WriteJson(JsonWriter& Writer) const
{
	Writer->WriteObjectStart();
	Writer->WriteIdentifierPrefix(TEXT("id")); WriteJsonValue(Writer, mId);
	Writer->WriteIdentifierPrefix(TEXT("repo_id")); WriteJsonValue(Writer, mRepo_id);
	Writer->WriteIdentifierPrefix(TEXT("user")); WriteJsonValue(Writer, mUser);
	Writer->WriteIdentifierPrefix(TEXT("base_ref")); WriteJsonValue(Writer, mBase_ref);
	Writer->WriteIdentifierPrefix(TEXT("other_ref")); WriteJsonValue(Writer, mOther_ref);
	Writer->WriteIdentifierPrefix(TEXT("ancestor_commit")); WriteJsonValue(Writer, mAncestor_commit);
	if (mBase_journal_ordinal_id.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("base_journal_ordinal_id")); WriteJsonValue(Writer, mBase_journal_ordinal_id.GetValue());
	}
	Writer->WriteIdentifierPrefix(TEXT("conflicts")); WriteJsonValue(Writer, mConflicts);
	Writer->WriteObjectEnd();
}

bool DetailedMerge::FromJson(const TSharedPtr<FJsonValue>& JsonValue)
{

	const TSharedPtr<FJsonObject>* InnerGeneratorOpenAPIObject;
	if (!JsonValue->TryGetObject(InnerGeneratorOpenAPIObject))
		return false;

	bool ParseSuccess = true;

    

	ParseSuccess &= TryGetJsonValue(*InnerGeneratorOpenAPIObject, TEXT("id"), mId);
	ParseSuccess &= TryGetJsonValue(*InnerGeneratorOpenAPIObject, TEXT("repo_id"), mRepo_id);
	ParseSuccess &= TryGetJsonValue(*InnerGeneratorOpenAPIObject, TEXT("user"), mUser);
	ParseSuccess &= TryGetJsonValue(*InnerGeneratorOpenAPIObject, TEXT("base_ref"), mBase_ref);
	ParseSuccess &= TryGetJsonValue(*InnerGeneratorOpenAPIObject, TEXT("other_ref"), mOther_ref);
	ParseSuccess &= TryGetJsonValue(*InnerGeneratorOpenAPIObject, TEXT("ancestor_commit"), mAncestor_commit);
    ParseSuccess &= TryGetJsonValue(*InnerGeneratorOpenAPIObject, TEXT("base_journal_ordinal_id"), mBase_journal_ordinal_id);
	ParseSuccess &= TryGetJsonValue(*InnerGeneratorOpenAPIObject, TEXT("conflicts"), mConflicts);


	return ParseSuccess;
}


}
}
}

