// Copyright 2024 Diversion Company, Inc. All Rights Reserved.
/**
 * Diversion Core API
 * Definition of the Core API used to access low-level functionality of Diversion
 *
 * The version of the OpenAPI document: 0.2.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.10.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "JsonBody.h"
#include "GetUserTierResponse.h"

namespace Diversion {
namespace CoreAPI {
namespace Model {



void GetUserTierResponse::WriteJson(JsonWriter& Writer) const
{
	Writer->WriteObjectStart();
	Writer->WriteIdentifierPrefix(TEXT("tier")); WriteJsonValue(Writer, mTier);
	Writer->WriteIdentifierPrefix(TEXT("has_stripe_customer")); WriteJsonValue(Writer, mHas_stripe_customer);
	Writer->WriteObjectEnd();
}

bool GetUserTierResponse::FromJson(const TSharedPtr<FJsonValue>& JsonValue)
{

	const TSharedPtr<FJsonObject>* InnerGeneratorOpenAPIObject;
	if (!JsonValue->TryGetObject(InnerGeneratorOpenAPIObject))
		return false;

	bool ParseSuccess = true;

    

	ParseSuccess &= TryGetJsonValue(*InnerGeneratorOpenAPIObject, TEXT("tier"), mTier);
	ParseSuccess &= TryGetJsonValue(*InnerGeneratorOpenAPIObject, TEXT("has_stripe_customer"), mHas_stripe_customer);


	return ParseSuccess;
}


}
}
}

