// Copyright 2024 Diversion Company, Inc. All Rights Reserved.
/**
 * Diversion Core API
 * Definition of the Core API used to access low-level functionality of Diversion
 *
 * OpenAPI spec version: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#include "OpenAPIGitRepoImport.h"

#include "CoreAPIModule.h"
#include "OpenAPIHelpers.h"

#include "Templates/SharedPointer.h"

namespace CoreAPI
{

void OpenAPIGitRepoImport::WriteJson(JsonWriter& Writer) const
{
	Writer->WriteObjectStart();
	if (GitUrl.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("git_url")); WriteJsonValue(Writer, GitUrl.GetValue());
	}
	if (ImportLevel.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("import_level")); WriteJsonValue(Writer, ImportLevel.GetValue());
	}
	if (GitBranch.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("git_branch")); WriteJsonValue(Writer, GitBranch.GetValue());
	}
	Writer->WriteObjectEnd();
}

bool OpenAPIGitRepoImport::FromJson(const TSharedPtr<FJsonValue>& JsonValue)
{
	const TSharedPtr<FJsonObject>* InnerGeneratorOpenAPIObject;
	if (!JsonValue->TryGetObject(InnerGeneratorOpenAPIObject))
		return false;

	bool ParseSuccess = true;

	ParseSuccess &= TryGetJsonValue(*InnerGeneratorOpenAPIObject, TEXT("git_url"), GitUrl);
	ParseSuccess &= TryGetJsonValue(*InnerGeneratorOpenAPIObject, TEXT("import_level"), ImportLevel);
	ParseSuccess &= TryGetJsonValue(*InnerGeneratorOpenAPIObject, TEXT("git_branch"), GitBranch);

	return ParseSuccess;
}

}
