// Copyright 2024 Diversion Company, Inc. All Rights Reserved.
/**
 * Diversion Core API
 * Definition of the Core API used to access low-level functionality of Diversion
 *
 * OpenAPI spec version: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#include "OpenAPIObjectStatus.h"

#include "CoreAPIModule.h"
#include "OpenAPIHelpers.h"

#include "Templates/SharedPointer.h"

namespace CoreAPI
{

inline FString ToString(const OpenAPIObjectStatus::Values& Value)
{
	switch (Value)
	{
	case OpenAPIObjectStatus::Values::Intact:
		return TEXT("Intact");
	case OpenAPIObjectStatus::Values::Added:
		return TEXT("Added");
	case OpenAPIObjectStatus::Values::Modified:
		return TEXT("Modified");
	case OpenAPIObjectStatus::Values::Deleted:
		return TEXT("Deleted");
	}

	UE_LOG(LogCoreAPI, Error, TEXT("Invalid OpenAPIObjectStatus::Values Value (%d)"), (int)Value);
	return TEXT("");
}

FString OpenAPIObjectStatus::EnumToString(const OpenAPIObjectStatus::Values& EnumValue)
{
	return ToString(EnumValue);
}

inline bool FromString(const FString& EnumAsString, OpenAPIObjectStatus::Values& Value)
{
	static TMap<FString, OpenAPIObjectStatus::Values> StringToEnum = { 
		{ TEXT("Intact"), OpenAPIObjectStatus::Values::Intact },
		{ TEXT("Added"), OpenAPIObjectStatus::Values::Added },
		{ TEXT("Modified"), OpenAPIObjectStatus::Values::Modified },
		{ TEXT("Deleted"), OpenAPIObjectStatus::Values::Deleted }, };

	const auto Found = StringToEnum.Find(EnumAsString);
	if(Found)
		Value = *Found;

	return Found != nullptr;
}

bool OpenAPIObjectStatus::EnumFromString(const FString& EnumAsString, OpenAPIObjectStatus::Values& EnumValue)
{
	return FromString(EnumAsString, EnumValue);
}

inline void WriteJsonValue(JsonWriter& Writer, const OpenAPIObjectStatus::Values& Value)
{
	WriteJsonValue(Writer, ToString(Value));
}

inline bool TryGetJsonValue(const TSharedPtr<FJsonValue>& JsonValue, OpenAPIObjectStatus::Values& Value)
{
	FString TmpValue;
	if (JsonValue->TryGetString(TmpValue))
	{
		if(FromString(TmpValue, Value))
			return true;
	}
	return false;
}

void OpenAPIObjectStatus::WriteJson(JsonWriter& Writer) const
{
	Writer->WriteObjectStart();
	Writer->WriteObjectEnd();
}

bool OpenAPIObjectStatus::FromJson(const TSharedPtr<FJsonValue>& JsonValue)
{
	const TSharedPtr<FJsonObject>* InnerGeneratorOpenAPIObject;
	if (!JsonValue->TryGetObject(InnerGeneratorOpenAPIObject))
		return false;

	bool ParseSuccess = true;


	return ParseSuccess;
}

}
