// Copyright 2024 Diversion Company, Inc. All Rights Reserved.
/**
 * Diversion Core API
 * Definition of the Core API used to access low-level functionality of Diversion
 *
 * OpenAPI spec version: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#include "OpenAPIRepositoryContentComparisonApi.h"

#include "OpenAPIRepositoryContentComparisonApiOperations.h"
#include "CoreAPIModule.h"

#include "HttpModule.h"
#include "Serialization/JsonSerializer.h"

namespace CoreAPI
{

OpenAPIRepositoryContentComparisonApi::OpenAPIRepositoryContentComparisonApi()
: Url(TEXT("https://api.diversion.dev/v0"))
{
}

OpenAPIRepositoryContentComparisonApi::~OpenAPIRepositoryContentComparisonApi() {}

void OpenAPIRepositoryContentComparisonApi::SetURL(const FString& InUrl)
{
	Url = InUrl;
}

void OpenAPIRepositoryContentComparisonApi::AddHeaderParam(const FString& Key, const FString& Value)
{
	AdditionalHeaderParams.Add(Key, Value);
}

void OpenAPIRepositoryContentComparisonApi::ClearHeaderParams()
{
	AdditionalHeaderParams.Reset();
}

bool OpenAPIRepositoryContentComparisonApi::IsValid() const
{
	if (Url.IsEmpty())
	{
		UE_LOG(LogCoreAPI, Error, TEXT("OpenAPIRepositoryContentComparisonApi: Endpoint Url is not set, request cannot be performed"));
		return false;
	}

	return true;
}

void OpenAPIRepositoryContentComparisonApi::SetHttpRetryManager(FHttpRetrySystem::FManager& InRetryManager)
{
	if (RetryManager != &InRetryManager)
	{
		DefaultRetryManager.Reset();
		RetryManager = &InRetryManager;
	}
}

FHttpRetrySystem::FManager& OpenAPIRepositoryContentComparisonApi::GetHttpRetryManager()
{
	checkf(RetryManager, TEXT("OpenAPIRepositoryContentComparisonApi: RetryManager is null.  You may have meant to set it with SetHttpRetryManager first, or you may not be using a custom RetryManager at all."))
	return *RetryManager;
}

FHttpRequestRef OpenAPIRepositoryContentComparisonApi::CreateHttpRequest(const Request& Request) const
{
	if (!Request.GetRetryParams().IsSet())
	{
		return FHttpModule::Get().CreateRequest();
	}
	else
	{
		if (!RetryManager)
		{
			// Create default retry manager if none was specified
			DefaultRetryManager = MakeUnique<HttpRetryManager>(6, 60);
			RetryManager = DefaultRetryManager.Get();
		}

		const HttpRetryParams& Params = Request.GetRetryParams().GetValue();
		return RetryManager->CreateRequest(Params.RetryLimitCountOverride, Params.RetryTimeoutRelativeSecondsOverride, Params.RetryResponseCodes, Params.RetryVerbs, Params.RetryDomains);
	}
}

void OpenAPIRepositoryContentComparisonApi::HandleResponse(FHttpResponsePtr HttpResponse, bool bSucceeded, Response& InOutResponse) const
{
	InOutResponse.SetHttpResponse(HttpResponse);
	InOutResponse.SetSuccessful(bSucceeded);

	if (bSucceeded && HttpResponse.IsValid())
	{
		InOutResponse.SetHttpResponseCode((EHttpResponseCodes::Type)HttpResponse->GetResponseCode());
		FString ContentType = HttpResponse->GetContentType();
		FString Content;

		if (ContentType.IsEmpty() || HttpResponse->GetContentLength() == 0)
		{
			return; // Nothing to parse
		}
		else if (ContentType.StartsWith(TEXT("application/json")) || ContentType.StartsWith("text/json"))
		{
			Content = HttpResponse->GetContentAsString();

			TSharedPtr<FJsonValue> JsonValue;
			auto Reader = TJsonReaderFactory<>::Create(Content);

			if (FJsonSerializer::Deserialize(Reader, JsonValue) && JsonValue.IsValid())
			{
				if (InOutResponse.FromJson(JsonValue))
					return; // Successfully parsed
			}
		}
		else if(ContentType.StartsWith(TEXT("text/plain")))
		{
			Content = HttpResponse->GetContentAsString();
			InOutResponse.SetResponseString(Content);
			return; // Successfully parsed
		}

		// Report the parse error but do not mark the request as unsuccessful. Data could be partial or malformed, but the request succeeded.
		UE_LOG(LogCoreAPI, Error, TEXT("Failed to deserialize Http response content (type:%s):\n%s"), *ContentType , *Content);
		return;
	}

	// By default, assume we failed to establish connection
	InOutResponse.SetHttpResponseCode(EHttpResponseCodes::RequestTimeout);
}

FHttpRequestPtr OpenAPIRepositoryContentComparisonApi::SrcHandlersv2TreeCompare(const SrcHandlersv2TreeCompareRequest& Request, const FSrcHandlersv2TreeCompareDelegate& Delegate /*= FSrcHandlersv2TreeCompareDelegate()*/, float InTimeoutSecs /*= -1.f*/) const
{
	if (!IsValid())
		return nullptr;

	FHttpRequestRef HttpRequest = CreateHttpRequest(Request);
	HttpRequest->SetURL(*(Url + Request.ComputePath()));

	for(const auto& It : AdditionalHeaderParams)
	{
		HttpRequest->SetHeader(It.Key, It.Value);
	}

	if(InTimeoutSecs > 0.f){
		HttpRequest->SetTimeout(InTimeoutSecs);
	}
	Request.SetupHttpRequest(HttpRequest);

	HttpRequest->OnProcessRequestComplete().BindSP(SharedThis(this), &OpenAPIRepositoryContentComparisonApi::OnSrcHandlersv2TreeCompareResponse, Delegate);
	HttpRequest->ProcessRequest();
	return HttpRequest;
}

void OpenAPIRepositoryContentComparisonApi::OnSrcHandlersv2TreeCompareResponse(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FSrcHandlersv2TreeCompareDelegate Delegate) const
{
	SrcHandlersv2TreeCompareResponse Response;
	HandleResponse(HttpResponse, bSucceeded, Response);
	Delegate.ExecuteIfBound(Response);
}

}
