// Copyright 2024 Diversion Company, Inc. All Rights Reserved.
/**
 * Diversion Core API
 * Definition of the Core API used to access low-level functionality of Diversion
 *
 * OpenAPI spec version: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#include "OpenAPIComparisonItem.h"

#include "CoreAPIModule.h"
#include "OpenAPIHelpers.h"

#include "Templates/SharedPointer.h"

namespace CoreAPI
{

void OpenAPIComparisonItem::WriteJson(JsonWriter& Writer) const
{
	Writer->WriteObjectStart();
	if (BaseItem.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("base_item")); WriteJsonValue(Writer, BaseItem.GetValue());
	}
	if (OtherItem.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("other_item")); WriteJsonValue(Writer, OtherItem.GetValue());
	}
	Writer->WriteIdentifierPrefix(TEXT("status")); WriteJsonValue(Writer, Status);
	Writer->WriteObjectEnd();
}

bool OpenAPIComparisonItem::FromJson(const TSharedPtr<FJsonValue>& JsonValue)
{
	const TSharedPtr<FJsonObject>* InnerGeneratorOpenAPIObject;
	if (!JsonValue->TryGetObject(InnerGeneratorOpenAPIObject))
		return false;

	bool ParseSuccess = true;

	ParseSuccess &= TryGetJsonValue(*InnerGeneratorOpenAPIObject, TEXT("base_item"), BaseItem);
	ParseSuccess &= TryGetJsonValue(*InnerGeneratorOpenAPIObject, TEXT("other_item"), OtherItem);
	ParseSuccess &= TryGetJsonValue(*InnerGeneratorOpenAPIObject, TEXT("status"), Status);

	return ParseSuccess;
}

}
