// Copyright 2024 Diversion Company, Inc. All Rights Reserved.
/**
 * Diversion Core API
 * Definition of the Core API used to access low-level functionality of Diversion
 *
 * OpenAPI spec version: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#include "OpenAPIGitSyncLevel.h"

#include "CoreAPIModule.h"
#include "OpenAPIHelpers.h"

#include "Templates/SharedPointer.h"

namespace CoreAPI
{

inline FString ToString(const OpenAPIGitSyncLevel::Values& Value)
{
	switch (Value)
	{
	case OpenAPIGitSyncLevel::Values::LatestCommit:
		return TEXT("LatestCommit");
	case OpenAPIGitSyncLevel::Values::DefaultBranch:
		return TEXT("DefaultBranch");
	case OpenAPIGitSyncLevel::Values::FullRepo:
		return TEXT("FullRepo");
	case OpenAPIGitSyncLevel::Values::FullRepoWithSync:
		return TEXT("FullRepoWithSync");
	}

	UE_LOG(LogCoreAPI, Error, TEXT("Invalid OpenAPIGitSyncLevel::Values Value (%d)"), (int)Value);
	return TEXT("");
}

FString OpenAPIGitSyncLevel::EnumToString(const OpenAPIGitSyncLevel::Values& EnumValue)
{
	return ToString(EnumValue);
}

inline bool FromString(const FString& EnumAsString, OpenAPIGitSyncLevel::Values& Value)
{
	static TMap<FString, OpenAPIGitSyncLevel::Values> StringToEnum = { 
		{ TEXT("LatestCommit"), OpenAPIGitSyncLevel::Values::LatestCommit },
		{ TEXT("DefaultBranch"), OpenAPIGitSyncLevel::Values::DefaultBranch },
		{ TEXT("FullRepo"), OpenAPIGitSyncLevel::Values::FullRepo },
		{ TEXT("FullRepoWithSync"), OpenAPIGitSyncLevel::Values::FullRepoWithSync }, };

	const auto Found = StringToEnum.Find(EnumAsString);
	if(Found)
		Value = *Found;

	return Found != nullptr;
}

bool OpenAPIGitSyncLevel::EnumFromString(const FString& EnumAsString, OpenAPIGitSyncLevel::Values& EnumValue)
{
	return FromString(EnumAsString, EnumValue);
}

inline void WriteJsonValue(JsonWriter& Writer, const OpenAPIGitSyncLevel::Values& Value)
{
	WriteJsonValue(Writer, ToString(Value));
}

inline bool TryGetJsonValue(const TSharedPtr<FJsonValue>& JsonValue, OpenAPIGitSyncLevel::Values& Value)
{
	FString TmpValue;
	if (JsonValue->TryGetString(TmpValue))
	{
		if(FromString(TmpValue, Value))
			return true;
	}
	return false;
}

void OpenAPIGitSyncLevel::WriteJson(JsonWriter& Writer) const
{
	Writer->WriteObjectStart();
	Writer->WriteObjectEnd();
}

bool OpenAPIGitSyncLevel::FromJson(const TSharedPtr<FJsonValue>& JsonValue)
{
	const TSharedPtr<FJsonObject>* InnerGeneratorOpenAPIObject;
	if (!JsonValue->TryGetObject(InnerGeneratorOpenAPIObject))
		return false;

	bool ParseSuccess = true;


	return ParseSuccess;
}

}
