// Copyright 2024 Diversion Company, Inc. All Rights Reserved.
/**
 * Diversion Core API
 * Definition of the Core API used to access low-level functionality of Diversion
 *
 * OpenAPI spec version: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#include "OpenAPIFileEntryBlob.h"

#include "CoreAPIModule.h"
#include "OpenAPIHelpers.h"

#include "Templates/SharedPointer.h"

namespace CoreAPI
{

void OpenAPIFileEntryBlob::WriteJson(JsonWriter& Writer) const
{
	Writer->WriteObjectStart();
	Writer->WriteIdentifierPrefix(TEXT("storage_uri")); WriteJsonValue(Writer, StorageUri);
	Writer->WriteIdentifierPrefix(TEXT("storage_backend")); WriteJsonValue(Writer, StorageBackend);
	Writer->WriteIdentifierPrefix(TEXT("size")); WriteJsonValue(Writer, Size);
	Writer->WriteIdentifierPrefix(TEXT("sha")); WriteJsonValue(Writer, Sha);
	Writer->WriteObjectEnd();
}

bool OpenAPIFileEntryBlob::FromJson(const TSharedPtr<FJsonValue>& JsonValue)
{
	const TSharedPtr<FJsonObject>* InnerGeneratorOpenAPIObject;
	if (!JsonValue->TryGetObject(InnerGeneratorOpenAPIObject))
		return false;

	bool ParseSuccess = true;

	ParseSuccess &= TryGetJsonValue(*InnerGeneratorOpenAPIObject, TEXT("storage_uri"), StorageUri);
	ParseSuccess &= TryGetJsonValue(*InnerGeneratorOpenAPIObject, TEXT("storage_backend"), StorageBackend);
	ParseSuccess &= TryGetJsonValue(*InnerGeneratorOpenAPIObject, TEXT("size"), Size);
	ParseSuccess &= TryGetJsonValue(*InnerGeneratorOpenAPIObject, TEXT("sha"), Sha);

	return ParseSuccess;
}

}
