// Copyright 2024 Diversion Company, Inc. All Rights Reserved.
/**
 * Diversion Core API
 * Definition of the Core API used to access low-level functionality of Diversion
 *
 * OpenAPI spec version: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#include "OpenAPIRepositoryMergeManipulationApi.h"

#include "OpenAPIRepositoryMergeManipulationApiOperations.h"
#include "CoreAPIModule.h"

#include "HttpModule.h"
#include "Serialization/JsonSerializer.h"

namespace CoreAPI
{

OpenAPIRepositoryMergeManipulationApi::OpenAPIRepositoryMergeManipulationApi()
: Url(TEXT("https://api.diversion.dev/v0"))
{
}

OpenAPIRepositoryMergeManipulationApi::~OpenAPIRepositoryMergeManipulationApi() {}

void OpenAPIRepositoryMergeManipulationApi::SetURL(const FString& InUrl)
{
	Url = InUrl;
}

void OpenAPIRepositoryMergeManipulationApi::AddHeaderParam(const FString& Key, const FString& Value)
{
	AdditionalHeaderParams.Add(Key, Value);
}

void OpenAPIRepositoryMergeManipulationApi::ClearHeaderParams()
{
	AdditionalHeaderParams.Reset();
}

bool OpenAPIRepositoryMergeManipulationApi::IsValid() const
{
	if (Url.IsEmpty())
	{
		UE_LOG(LogCoreAPI, Error, TEXT("OpenAPIRepositoryMergeManipulationApi: Endpoint Url is not set, request cannot be performed"));
		return false;
	}

	return true;
}

void OpenAPIRepositoryMergeManipulationApi::SetHttpRetryManager(FHttpRetrySystem::FManager& InRetryManager)
{
	if (RetryManager != &InRetryManager)
	{
		DefaultRetryManager.Reset();
		RetryManager = &InRetryManager;
	}
}

FHttpRetrySystem::FManager& OpenAPIRepositoryMergeManipulationApi::GetHttpRetryManager()
{
	checkf(RetryManager, TEXT("OpenAPIRepositoryMergeManipulationApi: RetryManager is null.  You may have meant to set it with SetHttpRetryManager first, or you may not be using a custom RetryManager at all."))
	return *RetryManager;
}

FHttpRequestRef OpenAPIRepositoryMergeManipulationApi::CreateHttpRequest(const Request& Request) const
{
	if (!Request.GetRetryParams().IsSet())
	{
		return FHttpModule::Get().CreateRequest();
	}
	else
	{
		if (!RetryManager)
		{
			// Create default retry manager if none was specified
			DefaultRetryManager = MakeUnique<HttpRetryManager>(6, 60);
			RetryManager = DefaultRetryManager.Get();
		}

		const HttpRetryParams& Params = Request.GetRetryParams().GetValue();
		return RetryManager->CreateRequest(Params.RetryLimitCountOverride, Params.RetryTimeoutRelativeSecondsOverride, Params.RetryResponseCodes, Params.RetryVerbs, Params.RetryDomains);
	}
}

void OpenAPIRepositoryMergeManipulationApi::HandleResponse(FHttpResponsePtr HttpResponse, bool bSucceeded, Response& InOutResponse) const
{
	InOutResponse.SetHttpResponse(HttpResponse);
	InOutResponse.SetSuccessful(bSucceeded);

	if (bSucceeded && HttpResponse.IsValid())
	{
		InOutResponse.SetHttpResponseCode((EHttpResponseCodes::Type)HttpResponse->GetResponseCode());
		FString ContentType = HttpResponse->GetContentType();
		FString Content;

		if (ContentType.IsEmpty() || HttpResponse->GetContentLength() == 0)
		{
			return; // Nothing to parse
		}
		else if (ContentType.StartsWith(TEXT("application/json")) || ContentType.StartsWith("text/json"))
		{
			Content = HttpResponse->GetContentAsString();

			TSharedPtr<FJsonValue> JsonValue;
			auto Reader = TJsonReaderFactory<>::Create(Content);

			if (FJsonSerializer::Deserialize(Reader, JsonValue) && JsonValue.IsValid())
			{
				if (InOutResponse.FromJson(JsonValue))
					return; // Successfully parsed
			}
		}
		else if(ContentType.StartsWith(TEXT("text/plain")))
		{
			Content = HttpResponse->GetContentAsString();
			InOutResponse.SetResponseString(Content);
			return; // Successfully parsed
		}

		// Report the parse error but do not mark the request as unsuccessful. Data could be partial or malformed, but the request succeeded.
		UE_LOG(LogCoreAPI, Error, TEXT("Failed to deserialize Http response content (type:%s):\n%s"), *ContentType , *Content);
		return;
	}

	// By default, assume we failed to establish connection
	InOutResponse.SetHttpResponseCode(EHttpResponseCodes::RequestTimeout);
}

FHttpRequestPtr OpenAPIRepositoryMergeManipulationApi::SrcHandlersv2MergeAcceptSide(const SrcHandlersv2MergeAcceptSideRequest& Request, const FSrcHandlersv2MergeAcceptSideDelegate& Delegate /*= FSrcHandlersv2MergeAcceptSideDelegate()*/, float InTimeoutSecs /*= -1.f*/) const
{
	if (!IsValid())
		return nullptr;

	FHttpRequestRef HttpRequest = CreateHttpRequest(Request);
	HttpRequest->SetURL(*(Url + Request.ComputePath()));

	for(const auto& It : AdditionalHeaderParams)
	{
		HttpRequest->SetHeader(It.Key, It.Value);
	}

	if(InTimeoutSecs > 0.f){
		HttpRequest->SetTimeout(InTimeoutSecs);
	}
	Request.SetupHttpRequest(HttpRequest);

	HttpRequest->OnProcessRequestComplete().BindSP(SharedThis(this), &OpenAPIRepositoryMergeManipulationApi::OnSrcHandlersv2MergeAcceptSideResponse, Delegate);
	HttpRequest->ProcessRequest();
	return HttpRequest;
}

void OpenAPIRepositoryMergeManipulationApi::OnSrcHandlersv2MergeAcceptSideResponse(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FSrcHandlersv2MergeAcceptSideDelegate Delegate) const
{
	SrcHandlersv2MergeAcceptSideResponse Response;
	HandleResponse(HttpResponse, bSucceeded, Response);
	Delegate.ExecuteIfBound(Response);
}

FHttpRequestPtr OpenAPIRepositoryMergeManipulationApi::SrcHandlersv2MergeCloseMerge(const SrcHandlersv2MergeCloseMergeRequest& Request, const FSrcHandlersv2MergeCloseMergeDelegate& Delegate /*= FSrcHandlersv2MergeCloseMergeDelegate()*/, float InTimeoutSecs /*= -1.f*/) const
{
	if (!IsValid())
		return nullptr;

	FHttpRequestRef HttpRequest = CreateHttpRequest(Request);
	HttpRequest->SetURL(*(Url + Request.ComputePath()));

	for(const auto& It : AdditionalHeaderParams)
	{
		HttpRequest->SetHeader(It.Key, It.Value);
	}

	if(InTimeoutSecs > 0.f){
		HttpRequest->SetTimeout(InTimeoutSecs);
	}
	Request.SetupHttpRequest(HttpRequest);

	HttpRequest->OnProcessRequestComplete().BindSP(SharedThis(this), &OpenAPIRepositoryMergeManipulationApi::OnSrcHandlersv2MergeCloseMergeResponse, Delegate);
	HttpRequest->ProcessRequest();
	return HttpRequest;
}

void OpenAPIRepositoryMergeManipulationApi::OnSrcHandlersv2MergeCloseMergeResponse(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FSrcHandlersv2MergeCloseMergeDelegate Delegate) const
{
	SrcHandlersv2MergeCloseMergeResponse Response;
	HandleResponse(HttpResponse, bSucceeded, Response);
	Delegate.ExecuteIfBound(Response);
}

FHttpRequestPtr OpenAPIRepositoryMergeManipulationApi::SrcHandlersv2MergeFinalize(const SrcHandlersv2MergeFinalizeRequest& Request, const FSrcHandlersv2MergeFinalizeDelegate& Delegate /*= FSrcHandlersv2MergeFinalizeDelegate()*/, float InTimeoutSecs /*= -1.f*/) const
{
	if (!IsValid())
		return nullptr;

	FHttpRequestRef HttpRequest = CreateHttpRequest(Request);
	HttpRequest->SetURL(*(Url + Request.ComputePath()));

	for(const auto& It : AdditionalHeaderParams)
	{
		HttpRequest->SetHeader(It.Key, It.Value);
	}

	if(InTimeoutSecs > 0.f){
		HttpRequest->SetTimeout(InTimeoutSecs);
	}
	Request.SetupHttpRequest(HttpRequest);

	HttpRequest->OnProcessRequestComplete().BindSP(SharedThis(this), &OpenAPIRepositoryMergeManipulationApi::OnSrcHandlersv2MergeFinalizeResponse, Delegate);
	HttpRequest->ProcessRequest();
	return HttpRequest;
}

void OpenAPIRepositoryMergeManipulationApi::OnSrcHandlersv2MergeFinalizeResponse(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FSrcHandlersv2MergeFinalizeDelegate Delegate) const
{
	SrcHandlersv2MergeFinalizeResponse Response;
	HandleResponse(HttpResponse, bSucceeded, Response);
	Delegate.ExecuteIfBound(Response);
}

FHttpRequestPtr OpenAPIRepositoryMergeManipulationApi::SrcHandlersv2MergeGetOpenMerge(const SrcHandlersv2MergeGetOpenMergeRequest& Request, const FSrcHandlersv2MergeGetOpenMergeDelegate& Delegate /*= FSrcHandlersv2MergeGetOpenMergeDelegate()*/, float InTimeoutSecs /*= -1.f*/) const
{
	if (!IsValid())
		return nullptr;

	FHttpRequestRef HttpRequest = CreateHttpRequest(Request);
	HttpRequest->SetURL(*(Url + Request.ComputePath()));

	for(const auto& It : AdditionalHeaderParams)
	{
		HttpRequest->SetHeader(It.Key, It.Value);
	}

	if(InTimeoutSecs > 0.f){
		HttpRequest->SetTimeout(InTimeoutSecs);
	}
	Request.SetupHttpRequest(HttpRequest);

	HttpRequest->OnProcessRequestComplete().BindSP(SharedThis(this), &OpenAPIRepositoryMergeManipulationApi::OnSrcHandlersv2MergeGetOpenMergeResponse, Delegate);
	HttpRequest->ProcessRequest();
	return HttpRequest;
}

void OpenAPIRepositoryMergeManipulationApi::OnSrcHandlersv2MergeGetOpenMergeResponse(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FSrcHandlersv2MergeGetOpenMergeDelegate Delegate) const
{
	SrcHandlersv2MergeGetOpenMergeResponse Response;
	HandleResponse(HttpResponse, bSucceeded, Response);
	Delegate.ExecuteIfBound(Response);
}

FHttpRequestPtr OpenAPIRepositoryMergeManipulationApi::SrcHandlersv2MergeListOpenMerges(const SrcHandlersv2MergeListOpenMergesRequest& Request, const FSrcHandlersv2MergeListOpenMergesDelegate& Delegate /*= FSrcHandlersv2MergeListOpenMergesDelegate()*/, float InTimeoutSecs /*= -1.f*/) const
{
	if (!IsValid())
		return nullptr;

	FHttpRequestRef HttpRequest = CreateHttpRequest(Request);
	HttpRequest->SetURL(*(Url + Request.ComputePath()));

	for(const auto& It : AdditionalHeaderParams)
	{
		HttpRequest->SetHeader(It.Key, It.Value);
	}

	if(InTimeoutSecs > 0.f){
		HttpRequest->SetTimeout(InTimeoutSecs);
	}
	Request.SetupHttpRequest(HttpRequest);

	HttpRequest->OnProcessRequestComplete().BindSP(SharedThis(this), &OpenAPIRepositoryMergeManipulationApi::OnSrcHandlersv2MergeListOpenMergesResponse, Delegate);
	HttpRequest->ProcessRequest();
	return HttpRequest;
}

void OpenAPIRepositoryMergeManipulationApi::OnSrcHandlersv2MergeListOpenMergesResponse(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FSrcHandlersv2MergeListOpenMergesDelegate Delegate) const
{
	SrcHandlersv2MergeListOpenMergesResponse Response;
	HandleResponse(HttpResponse, bSucceeded, Response);
	Delegate.ExecuteIfBound(Response);
}

FHttpRequestPtr OpenAPIRepositoryMergeManipulationApi::SrcHandlersv2MergeMergeRequest(const SrcHandlersv2MergeMergeRequestRequest& Request, const FSrcHandlersv2MergeMergeRequestDelegate& Delegate /*= FSrcHandlersv2MergeMergeRequestDelegate()*/, float InTimeoutSecs /*= -1.f*/) const
{
	if (!IsValid())
		return nullptr;

	FHttpRequestRef HttpRequest = CreateHttpRequest(Request);
	HttpRequest->SetURL(*(Url + Request.ComputePath()));

	for(const auto& It : AdditionalHeaderParams)
	{
		HttpRequest->SetHeader(It.Key, It.Value);
	}

	if(InTimeoutSecs > 0.f){
		HttpRequest->SetTimeout(InTimeoutSecs);
	}
	Request.SetupHttpRequest(HttpRequest);

	HttpRequest->OnProcessRequestComplete().BindSP(SharedThis(this), &OpenAPIRepositoryMergeManipulationApi::OnSrcHandlersv2MergeMergeRequestResponse, Delegate);
	HttpRequest->ProcessRequest();
	return HttpRequest;
}

void OpenAPIRepositoryMergeManipulationApi::OnSrcHandlersv2MergeMergeRequestResponse(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FSrcHandlersv2MergeMergeRequestDelegate Delegate) const
{
	SrcHandlersv2MergeMergeRequestResponse Response;
	HandleResponse(HttpResponse, bSucceeded, Response);
	Delegate.ExecuteIfBound(Response);
}

FHttpRequestPtr OpenAPIRepositoryMergeManipulationApi::SrcHandlersv2MergePost(const SrcHandlersv2MergePostRequest& Request, const FSrcHandlersv2MergePostDelegate& Delegate /*= FSrcHandlersv2MergePostDelegate()*/, float InTimeoutSecs /*= -1.f*/) const
{
	if (!IsValid())
		return nullptr;

	FHttpRequestRef HttpRequest = CreateHttpRequest(Request);
	HttpRequest->SetURL(*(Url + Request.ComputePath()));

	for(const auto& It : AdditionalHeaderParams)
	{
		HttpRequest->SetHeader(It.Key, It.Value);
	}

	if(InTimeoutSecs > 0.f){
		HttpRequest->SetTimeout(InTimeoutSecs);
	}
	Request.SetupHttpRequest(HttpRequest);

	HttpRequest->OnProcessRequestComplete().BindSP(SharedThis(this), &OpenAPIRepositoryMergeManipulationApi::OnSrcHandlersv2MergePostResponse, Delegate);
	HttpRequest->ProcessRequest();
	return HttpRequest;
}

void OpenAPIRepositoryMergeManipulationApi::OnSrcHandlersv2MergePostResponse(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FSrcHandlersv2MergePostDelegate Delegate) const
{
	SrcHandlersv2MergePostResponse Response;
	HandleResponse(HttpResponse, bSucceeded, Response);
	Delegate.ExecuteIfBound(Response);
}

FHttpRequestPtr OpenAPIRepositoryMergeManipulationApi::SrcHandlersv2MergeSetResult(const SrcHandlersv2MergeSetResultRequest& Request, const FSrcHandlersv2MergeSetResultDelegate& Delegate /*= FSrcHandlersv2MergeSetResultDelegate()*/, float InTimeoutSecs /*= -1.f*/) const
{
	if (!IsValid())
		return nullptr;

	FHttpRequestRef HttpRequest = CreateHttpRequest(Request);
	HttpRequest->SetURL(*(Url + Request.ComputePath()));

	for(const auto& It : AdditionalHeaderParams)
	{
		HttpRequest->SetHeader(It.Key, It.Value);
	}

	if(InTimeoutSecs > 0.f){
		HttpRequest->SetTimeout(InTimeoutSecs);
	}
	Request.SetupHttpRequest(HttpRequest);

	HttpRequest->OnProcessRequestComplete().BindSP(SharedThis(this), &OpenAPIRepositoryMergeManipulationApi::OnSrcHandlersv2MergeSetResultResponse, Delegate);
	HttpRequest->ProcessRequest();
	return HttpRequest;
}

void OpenAPIRepositoryMergeManipulationApi::OnSrcHandlersv2MergeSetResultResponse(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FSrcHandlersv2MergeSetResultDelegate Delegate) const
{
	SrcHandlersv2MergeSetResultResponse Response;
	HandleResponse(HttpResponse, bSucceeded, Response);
	Delegate.ExecuteIfBound(Response);
}

}
