// Copyright 2024 Diversion Company, Inc. All Rights Reserved.
/**
 * Diversion Core API
 * Definition of the Core API used to access low-level functionality of Diversion
 *
 * OpenAPI spec version: 0.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#include "OpenAPIRepositoryCommitManipulationApi.h"

#include "OpenAPIRepositoryCommitManipulationApiOperations.h"
#include "CoreAPIModule.h"

#include "HttpModule.h"
#include "Serialization/JsonSerializer.h"

namespace CoreAPI
{

OpenAPIRepositoryCommitManipulationApi::OpenAPIRepositoryCommitManipulationApi()
: Url(TEXT("https://api.diversion.dev/v0"))
{
}

OpenAPIRepositoryCommitManipulationApi::~OpenAPIRepositoryCommitManipulationApi() {}

void OpenAPIRepositoryCommitManipulationApi::SetURL(const FString& InUrl)
{
	Url = InUrl;
}

void OpenAPIRepositoryCommitManipulationApi::AddHeaderParam(const FString& Key, const FString& Value)
{
	AdditionalHeaderParams.Add(Key, Value);
}

void OpenAPIRepositoryCommitManipulationApi::ClearHeaderParams()
{
	AdditionalHeaderParams.Reset();
}

bool OpenAPIRepositoryCommitManipulationApi::IsValid() const
{
	if (Url.IsEmpty())
	{
		UE_LOG(LogCoreAPI, Error, TEXT("OpenAPIRepositoryCommitManipulationApi: Endpoint Url is not set, request cannot be performed"));
		return false;
	}

	return true;
}

void OpenAPIRepositoryCommitManipulationApi::SetHttpRetryManager(FHttpRetrySystem::FManager& InRetryManager)
{
	if (RetryManager != &InRetryManager)
	{
		DefaultRetryManager.Reset();
		RetryManager = &InRetryManager;
	}
}

FHttpRetrySystem::FManager& OpenAPIRepositoryCommitManipulationApi::GetHttpRetryManager()
{
	checkf(RetryManager, TEXT("OpenAPIRepositoryCommitManipulationApi: RetryManager is null.  You may have meant to set it with SetHttpRetryManager first, or you may not be using a custom RetryManager at all."))
	return *RetryManager;
}

FHttpRequestRef OpenAPIRepositoryCommitManipulationApi::CreateHttpRequest(const Request& Request) const
{
	if (!Request.GetRetryParams().IsSet())
	{
		return FHttpModule::Get().CreateRequest();
	}
	else
	{
		if (!RetryManager)
		{
			// Create default retry manager if none was specified
			DefaultRetryManager = MakeUnique<HttpRetryManager>(6, 60);
			RetryManager = DefaultRetryManager.Get();
		}

		const HttpRetryParams& Params = Request.GetRetryParams().GetValue();
		return RetryManager->CreateRequest(Params.RetryLimitCountOverride, Params.RetryTimeoutRelativeSecondsOverride, Params.RetryResponseCodes, Params.RetryVerbs, Params.RetryDomains);
	}
}

void OpenAPIRepositoryCommitManipulationApi::HandleResponse(FHttpResponsePtr HttpResponse, bool bSucceeded, Response& InOutResponse) const
{
	InOutResponse.SetHttpResponse(HttpResponse);
	InOutResponse.SetSuccessful(bSucceeded);

	if (bSucceeded && HttpResponse.IsValid())
	{
		InOutResponse.SetHttpResponseCode((EHttpResponseCodes::Type)HttpResponse->GetResponseCode());
		FString ContentType = HttpResponse->GetContentType();
		FString Content;

		if (ContentType.IsEmpty() || HttpResponse->GetContentLength() == 0)
		{
			return; // Nothing to parse
		}
		else if (ContentType.StartsWith(TEXT("application/json")) || ContentType.StartsWith("text/json"))
		{
			Content = HttpResponse->GetContentAsString();

			TSharedPtr<FJsonValue> JsonValue;
			auto Reader = TJsonReaderFactory<>::Create(Content);

			if (FJsonSerializer::Deserialize(Reader, JsonValue) && JsonValue.IsValid())
			{
				if (InOutResponse.FromJson(JsonValue))
					return; // Successfully parsed
			}
		}
		else if(ContentType.StartsWith(TEXT("text/plain")))
		{
			Content = HttpResponse->GetContentAsString();
			InOutResponse.SetResponseString(Content);
			return; // Successfully parsed
		}

		// Report the parse error but do not mark the request as unsuccessful. Data could be partial or malformed, but the request succeeded.
		UE_LOG(LogCoreAPI, Error, TEXT("Failed to deserialize Http response content (type:%s):\n%s"), *ContentType , *Content);
		return;
	}

	// By default, assume we failed to establish connection
	InOutResponse.SetHttpResponseCode(EHttpResponseCodes::RequestTimeout);
}

FHttpRequestPtr OpenAPIRepositoryCommitManipulationApi::SrcHandlersv2CommitGet(const SrcHandlersv2CommitGetRequest& Request, const FSrcHandlersv2CommitGetDelegate& Delegate /*= FSrcHandlersv2CommitGetDelegate()*/, float InTimeoutSecs /*= -1.f*/) const
{
	if (!IsValid())
		return nullptr;

	FHttpRequestRef HttpRequest = CreateHttpRequest(Request);
	HttpRequest->SetURL(*(Url + Request.ComputePath()));

	for(const auto& It : AdditionalHeaderParams)
	{
		HttpRequest->SetHeader(It.Key, It.Value);
	}

	if(InTimeoutSecs > 0.f){
		HttpRequest->SetTimeout(InTimeoutSecs);
	}
	Request.SetupHttpRequest(HttpRequest);

	HttpRequest->OnProcessRequestComplete().BindSP(SharedThis(this), &OpenAPIRepositoryCommitManipulationApi::OnSrcHandlersv2CommitGetResponse, Delegate);
	HttpRequest->ProcessRequest();
	return HttpRequest;
}

void OpenAPIRepositoryCommitManipulationApi::OnSrcHandlersv2CommitGetResponse(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FSrcHandlersv2CommitGetDelegate Delegate) const
{
	SrcHandlersv2CommitGetResponse Response;
	HandleResponse(HttpResponse, bSucceeded, Response);
	Delegate.ExecuteIfBound(Response);
}

FHttpRequestPtr OpenAPIRepositoryCommitManipulationApi::SrcHandlersv2CommitGetBulk(const SrcHandlersv2CommitGetBulkRequest& Request, const FSrcHandlersv2CommitGetBulkDelegate& Delegate /*= FSrcHandlersv2CommitGetBulkDelegate()*/, float InTimeoutSecs /*= -1.f*/) const
{
	if (!IsValid())
		return nullptr;

	FHttpRequestRef HttpRequest = CreateHttpRequest(Request);
	HttpRequest->SetURL(*(Url + Request.ComputePath()));

	for(const auto& It : AdditionalHeaderParams)
	{
		HttpRequest->SetHeader(It.Key, It.Value);
	}

	if(InTimeoutSecs > 0.f){
		HttpRequest->SetTimeout(InTimeoutSecs);
	}
	Request.SetupHttpRequest(HttpRequest);

	HttpRequest->OnProcessRequestComplete().BindSP(SharedThis(this), &OpenAPIRepositoryCommitManipulationApi::OnSrcHandlersv2CommitGetBulkResponse, Delegate);
	HttpRequest->ProcessRequest();
	return HttpRequest;
}

void OpenAPIRepositoryCommitManipulationApi::OnSrcHandlersv2CommitGetBulkResponse(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FSrcHandlersv2CommitGetBulkDelegate Delegate) const
{
	SrcHandlersv2CommitGetBulkResponse Response;
	HandleResponse(HttpResponse, bSucceeded, Response);
	Delegate.ExecuteIfBound(Response);
}

FHttpRequestPtr OpenAPIRepositoryCommitManipulationApi::SrcHandlersv2CommitListAll(const SrcHandlersv2CommitListAllRequest& Request, const FSrcHandlersv2CommitListAllDelegate& Delegate /*= FSrcHandlersv2CommitListAllDelegate()*/, float InTimeoutSecs /*= -1.f*/) const
{
	if (!IsValid())
		return nullptr;

	FHttpRequestRef HttpRequest = CreateHttpRequest(Request);
	HttpRequest->SetURL(*(Url + Request.ComputePath()));

	for(const auto& It : AdditionalHeaderParams)
	{
		HttpRequest->SetHeader(It.Key, It.Value);
	}

	if(InTimeoutSecs > 0.f){
		HttpRequest->SetTimeout(InTimeoutSecs);
	}
	Request.SetupHttpRequest(HttpRequest);

	HttpRequest->OnProcessRequestComplete().BindSP(SharedThis(this), &OpenAPIRepositoryCommitManipulationApi::OnSrcHandlersv2CommitListAllResponse, Delegate);
	HttpRequest->ProcessRequest();
	return HttpRequest;
}

void OpenAPIRepositoryCommitManipulationApi::OnSrcHandlersv2CommitListAllResponse(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FSrcHandlersv2CommitListAllDelegate Delegate) const
{
	SrcHandlersv2CommitListAllResponse Response;
	HandleResponse(HttpResponse, bSucceeded, Response);
	Delegate.ExecuteIfBound(Response);
}

FHttpRequestPtr OpenAPIRepositoryCommitManipulationApi::SrcHandlersv2CommitPatch(const SrcHandlersv2CommitPatchRequest& Request, const FSrcHandlersv2CommitPatchDelegate& Delegate /*= FSrcHandlersv2CommitPatchDelegate()*/, float InTimeoutSecs /*= -1.f*/) const
{
	if (!IsValid())
		return nullptr;

	FHttpRequestRef HttpRequest = CreateHttpRequest(Request);
	HttpRequest->SetURL(*(Url + Request.ComputePath()));

	for(const auto& It : AdditionalHeaderParams)
	{
		HttpRequest->SetHeader(It.Key, It.Value);
	}

	if(InTimeoutSecs > 0.f){
		HttpRequest->SetTimeout(InTimeoutSecs);
	}
	Request.SetupHttpRequest(HttpRequest);

	HttpRequest->OnProcessRequestComplete().BindSP(SharedThis(this), &OpenAPIRepositoryCommitManipulationApi::OnSrcHandlersv2CommitPatchResponse, Delegate);
	HttpRequest->ProcessRequest();
	return HttpRequest;
}

void OpenAPIRepositoryCommitManipulationApi::OnSrcHandlersv2CommitPatchResponse(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FSrcHandlersv2CommitPatchDelegate Delegate) const
{
	SrcHandlersv2CommitPatchResponse Response;
	HandleResponse(HttpResponse, bSucceeded, Response);
	Delegate.ExecuteIfBound(Response);
}

FHttpRequestPtr OpenAPIRepositoryCommitManipulationApi::SrcHandlersv2RevertRevert(const SrcHandlersv2RevertRevertRequest& Request, const FSrcHandlersv2RevertRevertDelegate& Delegate /*= FSrcHandlersv2RevertRevertDelegate()*/, float InTimeoutSecs /*= -1.f*/) const
{
	if (!IsValid())
		return nullptr;

	FHttpRequestRef HttpRequest = CreateHttpRequest(Request);
	HttpRequest->SetURL(*(Url + Request.ComputePath()));

	for(const auto& It : AdditionalHeaderParams)
	{
		HttpRequest->SetHeader(It.Key, It.Value);
	}

	if(InTimeoutSecs > 0.f){
		HttpRequest->SetTimeout(InTimeoutSecs);
	}
	Request.SetupHttpRequest(HttpRequest);

	HttpRequest->OnProcessRequestComplete().BindSP(SharedThis(this), &OpenAPIRepositoryCommitManipulationApi::OnSrcHandlersv2RevertRevertResponse, Delegate);
	HttpRequest->ProcessRequest();
	return HttpRequest;
}

void OpenAPIRepositoryCommitManipulationApi::OnSrcHandlersv2RevertRevertResponse(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FSrcHandlersv2RevertRevertDelegate Delegate) const
{
	SrcHandlersv2RevertRevertResponse Response;
	HandleResponse(HttpResponse, bSucceeded, Response);
	Delegate.ExecuteIfBound(Response);
}

FHttpRequestPtr OpenAPIRepositoryCommitManipulationApi::SrcHandlersv2WorkspaceCommitWorkspace(const SrcHandlersv2WorkspaceCommitWorkspaceRequest& Request, const FSrcHandlersv2WorkspaceCommitWorkspaceDelegate& Delegate /*= FSrcHandlersv2WorkspaceCommitWorkspaceDelegate()*/, float InTimeoutSecs /*= -1.f*/) const
{
	if (!IsValid())
		return nullptr;

	FHttpRequestRef HttpRequest = CreateHttpRequest(Request);
	HttpRequest->SetURL(*(Url + Request.ComputePath()));

	for(const auto& It : AdditionalHeaderParams)
	{
		HttpRequest->SetHeader(It.Key, It.Value);
	}

	if(InTimeoutSecs > 0.f){
		HttpRequest->SetTimeout(InTimeoutSecs);
	}
	Request.SetupHttpRequest(HttpRequest);

	HttpRequest->OnProcessRequestComplete().BindSP(SharedThis(this), &OpenAPIRepositoryCommitManipulationApi::OnSrcHandlersv2WorkspaceCommitWorkspaceResponse, Delegate);
	HttpRequest->ProcessRequest();
	return HttpRequest;
}

void OpenAPIRepositoryCommitManipulationApi::OnSrcHandlersv2WorkspaceCommitWorkspaceResponse(FHttpRequestPtr HttpRequest, FHttpResponsePtr HttpResponse, bool bSucceeded, FSrcHandlersv2WorkspaceCommitWorkspaceDelegate Delegate) const
{
	SrcHandlersv2WorkspaceCommitWorkspaceResponse Response;
	HandleResponse(HttpResponse, bSucceeded, Response);
	Delegate.ExecuteIfBound(Response);
}

}
