// Copyright 2024 Diversion Company, Inc. All Rights Reserved.
/**
 * Diversion Core API
 * Definition of the Core API used to access low-level functionality of Diversion
 *
 * The version of the OpenAPI document: 0.2.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.10.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "JsonBody.h"
#include "OrganizationMember.h"

namespace Diversion {
namespace CoreAPI {
namespace Model {



void OrganizationMember::WriteJson(JsonWriter& Writer) const
{
	Writer->WriteObjectStart();
	Writer->WriteIdentifierPrefix(TEXT("id")); WriteJsonValue(Writer, mId);
	Writer->WriteIdentifierPrefix(TEXT("user_id")); WriteJsonValue(Writer, mUser_id);
	Writer->WriteIdentifierPrefix(TEXT("organization_id")); WriteJsonValue(Writer, mOrganization_id);
	Writer->WriteIdentifierPrefix(TEXT("role")); WriteJsonValue(Writer, mRole);
	Writer->WriteObjectEnd();
}

bool OrganizationMember::FromJson(const TSharedPtr<FJsonValue>& JsonValue)
{

	const TSharedPtr<FJsonObject>* InnerGeneratorOpenAPIObject;
	if (!JsonValue->TryGetObject(InnerGeneratorOpenAPIObject))
		return false;

	bool ParseSuccess = true;

    

	ParseSuccess &= TryGetJsonValue(*InnerGeneratorOpenAPIObject, TEXT("id"), mId);
	ParseSuccess &= TryGetJsonValue(*InnerGeneratorOpenAPIObject, TEXT("user_id"), mUser_id);
	ParseSuccess &= TryGetJsonValue(*InnerGeneratorOpenAPIObject, TEXT("organization_id"), mOrganization_id);
	ParseSuccess &= TryGetJsonValue(*InnerGeneratorOpenAPIObject, TEXT("role"), mRole);


	return ParseSuccess;
}


}
}
}

