// Copyright 2024 Diversion Company, Inc. All Rights Reserved.
/**
 * Diversion Core API
 * Definition of the Core API used to access low-level functionality of Diversion
 *
 * The version of the OpenAPI document: 0.2.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.10.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "JsonBody.h"
#include "PartNumberToUrl.h"

namespace Diversion {
namespace CoreAPI {
namespace Model {



void PartNumberToUrl::WriteJson(JsonWriter& Writer) const
{
	Writer->WriteObjectStart();
	Writer->WriteIdentifierPrefix(TEXT("part_number")); WriteJsonValue(Writer, mPart_number);
	Writer->WriteIdentifierPrefix(TEXT("upload_url")); WriteJsonValue(Writer, mUpload_url);
	Writer->WriteObjectEnd();
}

bool PartNumberToUrl::FromJson(const TSharedPtr<FJsonValue>& JsonValue)
{

	const TSharedPtr<FJsonObject>* InnerGeneratorOpenAPIObject;
	if (!JsonValue->TryGetObject(InnerGeneratorOpenAPIObject))
		return false;

	bool ParseSuccess = true;

    

	ParseSuccess &= TryGetJsonValue(*InnerGeneratorOpenAPIObject, TEXT("part_number"), mPart_number);
	ParseSuccess &= TryGetJsonValue(*InnerGeneratorOpenAPIObject, TEXT("upload_url"), mUpload_url);


	return ParseSuccess;
}


}
}
}

