// Copyright 2024 Diversion Company, Inc. All Rights Reserved.
/**
 * Diversion Core API
 * Definition of the Core API used to access low-level functionality of Diversion
 *
 * The version of the OpenAPI document: 0.2.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.10.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


#include "RepositoryManipulationApi.h"
#include "HTTPResult.h"
#include "JsonBody.h"

#include "Types.h"


namespace Diversion {
namespace CoreAPI {

using namespace Diversion::CoreAPI::Model;

RepositoryManipulationApi::RepositoryManipulationApi(TSharedPtr<DiversionHttp::FHttpRequestManager> InApiClient)
     : ApiClient(InApiClient) {}

RepositoryManipulationApi::~RepositoryManipulationApi() {}



THTTPResult<TVariant<TSharedPtr<Src_handlersv2_commit_get_object_history_200_response>, TSharedPtr<Error>>> RepositoryManipulationApi::SrcHandlersv2CommitGetObjectHistory(FString repoId, FString refId, FString path, TOptional<int32_t> limit, TOptional<int32_t> skip, 
        const FString& Token,
        const TMap<FString, FString>& Headers,
		int ConnectionTimeoutSeconds, int RequestTimeoutSeconds) const
{

    FString URL = TEXT("/v0/repos/{repo_id}/files/history/{ref_id}/{path}");
    URL.ReplaceInline(TEXT("{repo_id}"), *DiversionHttp::URLEncode(DiversionHttp::parameterToString(repoId)));
    URL.ReplaceInline(TEXT("{ref_id}"), *DiversionHttp::URLEncode(DiversionHttp::parameterToString(refId)));
    URL.ReplaceInline(TEXT("{path}"), *DiversionHttp::URLEncode(DiversionHttp::parameterToString(path)));

    TMap<FString, FString> localVarQueryParams;
    TMap<FString, FString> localVarFormParams;
    //TMap<FString, TSharedPtr<HttpContent>> localVarFileParams;

    
    TSet<FString> localVarResponseHttpContentTypes;
    localVarResponseHttpContentTypes.Add(TEXT("application/json"));

    FString localVarResponseHttpContentType;

    // use JSON if possible
    if (localVarResponseHttpContentTypes.Num() == 0)
    {
        localVarResponseHttpContentType = TEXT("application/json");
    }
    // JSON
    else if (localVarResponseHttpContentTypes.Contains(TEXT("application/json")))
    {
        localVarResponseHttpContentType = TEXT("application/json");
    }
    else
    {
        return THTTPResult<TVariant<TSharedPtr<Src_handlersv2_commit_get_object_history_200_response>, TSharedPtr<Error>>>::Failure(TEXT("RepositoryManipulationApi->SrcHandlersv2CommitGetObjectHistory does not produce any supported media type"), 400, {});
    }

    // TODO: Add this to the headers
    //Headers[TEXT("Accept")] = localVarResponseHttpContentType;

    TSet<FString> localVarConsumeHttpContentTypes;

    if (limit.IsSet())
    {
        localVarQueryParams.Add(TEXT("limit"), DiversionHttp::URLEncode(DiversionHttp::parameterToString(limit.Get(0))));
    }
    if (skip.IsSet())
    {
        localVarQueryParams.Add(TEXT("skip"), DiversionHttp::URLEncode(DiversionHttp::parameterToString(skip.Get(0))));
    }

    FString Content = TEXT("");
    // TSharedPtr<IHttpBody> localVarHttpBody;
    FString localVarRequestHttpContentType;

    // use JSON if possible
    if (localVarConsumeHttpContentTypes.Num() == 0 || localVarConsumeHttpContentTypes.Contains(TEXT("application/json")))
    {
        localVarRequestHttpContentType = TEXT("application/json");
    }
    else
    {
        return THTTPResult<TVariant<TSharedPtr<Src_handlersv2_commit_get_object_history_200_response>, TSharedPtr<Error>>>::Failure(TEXT("RepositoryManipulationApi->SrcHandlersv2CommitGetObjectHistory does not consume any supported media type"), 415, {});
    }

    // Add query params
    if (localVarQueryParams.Num() > 0) {
        URL += TEXT("?");
        FString QueryParams;
        for (const auto& Param : localVarQueryParams)
        {
            QueryParams += Param.Key + TEXT("=") + Param.Value + TEXT("&");
        }
        QueryParams.RemoveFromEnd(TEXT("&"));
        URL += QueryParams;
    }

    DiversionHttp::HTTPCallResponse Response = ApiClient->SendRequest(URL, DiversionHttp::HttpMethod::GET, Token, localVarRequestHttpContentType, 
        Content, Headers, ConnectionTimeoutSeconds, RequestTimeoutSeconds);

    // TODO: Add validation - check response content type
    
    if (Response.ResponseCode == 200) {
        if(localVarResponseHttpContentType == TEXT("application/json"))
        {
            TSharedPtr<Src_handlersv2_commit_get_object_history_200_response> localVarResult = MakeShared<Src_handlersv2_commit_get_object_history_200_response>();
            TSharedPtr<FJsonValue> JsonValue;
            TSharedRef<TJsonReader<>> JsonReader = TJsonReaderFactory<>::Create(Response.Contents);
            if (!FJsonSerializer::Deserialize(JsonReader, JsonValue) || !JsonValue.IsValid())
            {
                return THTTPResult<TVariant<TSharedPtr<Src_handlersv2_commit_get_object_history_200_response>, TSharedPtr<Error>>>::Failure(TEXT("error calling src_handlersv2_commit_getObjectHistory: JSON reader failed parsing the response string"), 500, Response.Headers);
            }

            
            if (localVarResult->FromJson(JsonValue)) {
                TVariant<TSharedPtr<Src_handlersv2_commit_get_object_history_200_response>, TSharedPtr<Error>> variantResult;
                variantResult.Emplace<TSharedPtr<Src_handlersv2_commit_get_object_history_200_response>>(localVarResult);
                return THTTPResult<TVariant<TSharedPtr<Src_handlersv2_commit_get_object_history_200_response>, TSharedPtr<Error>>>::Success(TOptional(variantResult), Response.ResponseCode, Response.Headers);
            }
            else {
                return THTTPResult<TVariant<TSharedPtr<Src_handlersv2_commit_get_object_history_200_response>, TSharedPtr<Error>>>::Failure(TEXT("error calling src_handlersv2_commit_getObjectHistory: JSON response was not in the expected format"), 500, Response.Headers);
            }
        }


        else
        {
            return THTTPResult<TVariant<TSharedPtr<Src_handlersv2_commit_get_object_history_200_response>, TSharedPtr<Error>>>::Failure(TEXT("error calling src_handlersv2_commit_getObjectHistory: unsupported response type"), 500, Response.Headers);
        }
    }
    if (Response.ResponseCode == 404) {
            FString ErrorMessage = TEXT("General Failure");
            if(Response.Error.IsSet()) {
                ErrorMessage = Response.Error.GetValue();
            } 
            // Try parsing as JSON
            else if(!Response.Contents.IsEmpty()) {
                if(localVarResponseHttpContentType == TEXT("application/json"))
                {
                    TSharedPtr<Error> localVarResult = MakeShared<Error>();
                    TSharedPtr<FJsonValue> JsonValue;
                    TSharedRef<TJsonReader<>> JsonReader = TJsonReaderFactory<>::Create(Response.Contents);
                    if (!FJsonSerializer::Deserialize(JsonReader, JsonValue) || !JsonValue.IsValid())
                    {
                        ErrorMessage = TEXT("Received corrupted error data");
                    }
                    
                    if (localVarResult->FromJson(JsonValue)) {
                        TVariant<TSharedPtr<Src_handlersv2_commit_get_object_history_200_response>, TSharedPtr<Error>> variantResult;
                        variantResult.Emplace<TSharedPtr<Error>>(localVarResult);
                        return THTTPResult<TVariant<TSharedPtr<Src_handlersv2_commit_get_object_history_200_response>, TSharedPtr<Error>>>::Failure(TEXT("ParsedJsonError"), Response.ResponseCode, Response.Headers, TOptional(variantResult));
                    }
                    else {
                        ErrorMessage = TEXT("Received corrupted error data");
                    }
                }
            }
            FString CurrError = TEXT("error calling src_handlersv2_commit_getObjectHistory: ") + ErrorMessage;
            return THTTPResult<TVariant<TSharedPtr<Src_handlersv2_commit_get_object_history_200_response>, TSharedPtr<Error>>>::Failure(CurrError, Response.ResponseCode, Response.Headers);

    }
    if (Response.ResponseCode == 0) {
        if(localVarResponseHttpContentType == TEXT("application/json"))
        {
            TSharedPtr<Error> localVarResult = MakeShared<Error>();
            TSharedPtr<FJsonValue> JsonValue;
            TSharedRef<TJsonReader<>> JsonReader = TJsonReaderFactory<>::Create(Response.Contents);
            if (!FJsonSerializer::Deserialize(JsonReader, JsonValue) || !JsonValue.IsValid())
            {
                return THTTPResult<TVariant<TSharedPtr<Src_handlersv2_commit_get_object_history_200_response>, TSharedPtr<Error>>>::Failure(TEXT("error calling src_handlersv2_commit_getObjectHistory: JSON reader failed parsing the response string"), 500, Response.Headers);
            }

            
            if (localVarResult->FromJson(JsonValue)) {
                TVariant<TSharedPtr<Src_handlersv2_commit_get_object_history_200_response>, TSharedPtr<Error>> variantResult;
                variantResult.Emplace<TSharedPtr<Error>>(localVarResult);
                return THTTPResult<TVariant<TSharedPtr<Src_handlersv2_commit_get_object_history_200_response>, TSharedPtr<Error>>>::Success(TOptional(variantResult), Response.ResponseCode, Response.Headers);
            }
            else {
                return THTTPResult<TVariant<TSharedPtr<Src_handlersv2_commit_get_object_history_200_response>, TSharedPtr<Error>>>::Failure(TEXT("error calling src_handlersv2_commit_getObjectHistory: JSON response was not in the expected format"), 500, Response.Headers);
            }
        }


        else
        {
            return THTTPResult<TVariant<TSharedPtr<Src_handlersv2_commit_get_object_history_200_response>, TSharedPtr<Error>>>::Failure(TEXT("error calling src_handlersv2_commit_getObjectHistory: unsupported response type"), 500, Response.Headers);
        }
    }


    if (Response.ResponseCode >= 400)
    {
            FString ErrorMessage = TEXT("General Failure");
            if(Response.Error.IsSet()) {
                ErrorMessage = Response.Error.GetValue();
            } 
            else if(!Response.Contents.IsEmpty()) {
                // Try parsing as JSON
                TSharedPtr<FJsonObject> JsonObject;
                TSharedRef<TJsonReader<>> JsonReader = TJsonReaderFactory<>::Create(Response.Contents);
                if (FJsonSerializer::Deserialize(JsonReader, JsonObject) 
                    && JsonObject.IsValid())
                {
                    if (JsonObject->HasField(TEXT("error_message"))) {
                        ErrorMessage = JsonObject->GetStringField(TEXT("error_message"));
                    }
                    else {
                        // Treat it as an error string 
                        ErrorMessage = Response.Contents;
                    }
                }
                else {
                    // Treat it as an error string 
                    ErrorMessage = Response.Contents;
                }
            }

            FString CurrError = TEXT("error calling src_handlersv2_commit_getObjectHistory: ") + ErrorMessage;
            return THTTPResult<TVariant<TSharedPtr<Src_handlersv2_commit_get_object_history_200_response>, TSharedPtr<Error>>>::Failure(CurrError, Response.ResponseCode, Response.Headers);
    }

    // Unepxected response code - TODO: try parse as any of the expected response types
    return THTTPResult<TVariant<TSharedPtr<Src_handlersv2_commit_get_object_history_200_response>, TSharedPtr<Error>>>::Failure(TEXT("error calling SrcHandlersv2CommitGetObjectHistory: unexpected response code"), Response.ResponseCode, Response.Headers);
}



THTTPResult<TVariant<TSharedPtr<HttpContent>, void*>> RepositoryManipulationApi::SrcHandlersv2FilesGetBlob(FString repoId, FString refId, FString path, 
        const FString& Token,
        const TMap<FString, FString>& Headers,
		int ConnectionTimeoutSeconds, int RequestTimeoutSeconds) const
{

    FString URL = TEXT("/v0/repos/{repo_id}/blobs/{ref_id}/{path}");
    URL.ReplaceInline(TEXT("{repo_id}"), *DiversionHttp::URLEncode(DiversionHttp::parameterToString(repoId)));
    URL.ReplaceInline(TEXT("{ref_id}"), *DiversionHttp::URLEncode(DiversionHttp::parameterToString(refId)));
    URL.ReplaceInline(TEXT("{path}"), *DiversionHttp::URLEncode(DiversionHttp::parameterToString(path)));

    TMap<FString, FString> localVarQueryParams;
    TMap<FString, FString> localVarFormParams;
    //TMap<FString, TSharedPtr<HttpContent>> localVarFileParams;

    
    TSet<FString> localVarResponseHttpContentTypes;
    localVarResponseHttpContentTypes.Add(TEXT("application/octet-stream"));

    FString localVarResponseHttpContentType;

    // use JSON if possible
    if (localVarResponseHttpContentTypes.Num() == 0)
    {
        localVarResponseHttpContentType = TEXT("application/json");
    }
    // JSON
    else if (localVarResponseHttpContentTypes.Contains(TEXT("application/json")))
    {
        localVarResponseHttpContentType = TEXT("application/json");
    }
    else
    {
        //It's going to be binary, so just use the first one.
        localVarResponseHttpContentType = *localVarResponseHttpContentTypes.begin();
    }

    // TODO: Add this to the headers
    //Headers[TEXT("Accept")] = localVarResponseHttpContentType;

    TSet<FString> localVarConsumeHttpContentTypes;


    FString Content = TEXT("");
    // TSharedPtr<IHttpBody> localVarHttpBody;
    FString localVarRequestHttpContentType;

    // use JSON if possible
    if (localVarConsumeHttpContentTypes.Num() == 0 || localVarConsumeHttpContentTypes.Contains(TEXT("application/json")))
    {
        localVarRequestHttpContentType = TEXT("application/json");
    }
    else
    {
        return THTTPResult<TVariant<TSharedPtr<HttpContent>, void*>>::Failure(TEXT("RepositoryManipulationApi->SrcHandlersv2FilesGetBlob does not consume any supported media type"), 415, {});
    }

    // Add query params
    if (localVarQueryParams.Num() > 0) {
        URL += TEXT("?");
        FString QueryParams;
        for (const auto& Param : localVarQueryParams)
        {
            QueryParams += Param.Key + TEXT("=") + Param.Value + TEXT("&");
        }
        QueryParams.RemoveFromEnd(TEXT("&"));
        URL += QueryParams;
    }

    DiversionHttp::HTTPCallResponse Response = ApiClient->SendRequest(URL, DiversionHttp::HttpMethod::GET, Token, localVarRequestHttpContentType, 
        Content, Headers, ConnectionTimeoutSeconds, RequestTimeoutSeconds);

    // TODO: Add validation - check response content type
    
    if (Response.ResponseCode == 200) {
        if(localVarResponseHttpContentType == TEXT("application/octet-stream"))
        {
            TVariant<TSharedPtr<HttpContent>, void*> variantResult;
            TSharedPtr<HttpContent> localVarResult = MakeShared<HttpContent>();
            localVarResult->FromString(Response.Contents);
            variantResult.Emplace<TSharedPtr<HttpContent>>(localVarResult);
            return THTTPResult<TVariant<TSharedPtr<HttpContent>, void*>>::Success(TOptional(variantResult), Response.ResponseCode, Response.Headers);
        }

        else
        {
            return THTTPResult<TVariant<TSharedPtr<HttpContent>, void*>>::Failure(TEXT("error calling src_handlersv2_files_getBlob: unsupported response type"), 500, Response.Headers);
        }
    }
    if (Response.ResponseCode == 204) {
        TVariant<TSharedPtr<HttpContent>, void*> variantResult;
        variantResult.Emplace<void*>(nullptr);
        return THTTPResult<TVariant<TSharedPtr<HttpContent>, void*>>::Success(TOptional(variantResult), Response.ResponseCode, Response.Headers);

    }


    if (Response.ResponseCode >= 400)
    {
            FString ErrorMessage = TEXT("General Failure");
            if(Response.Error.IsSet()) {
                ErrorMessage = Response.Error.GetValue();
            } 
            else if(!Response.Contents.IsEmpty()) {
                // Try parsing as JSON
                TSharedPtr<FJsonObject> JsonObject;
                TSharedRef<TJsonReader<>> JsonReader = TJsonReaderFactory<>::Create(Response.Contents);
                if (FJsonSerializer::Deserialize(JsonReader, JsonObject) 
                    && JsonObject.IsValid())
                {
                    if (JsonObject->HasField(TEXT("error_message"))) {
                        ErrorMessage = JsonObject->GetStringField(TEXT("error_message"));
                    }
                    else {
                        // Treat it as an error string 
                        ErrorMessage = Response.Contents;
                    }
                }
                else {
                    // Treat it as an error string 
                    ErrorMessage = Response.Contents;
                }
            }

            FString CurrError = TEXT("error calling src_handlersv2_files_getBlob: ") + ErrorMessage;
            return THTTPResult<TVariant<TSharedPtr<HttpContent>, void*>>::Failure(CurrError, Response.ResponseCode, Response.Headers);
    }

    // Unepxected response code - TODO: try parse as any of the expected response types
    return THTTPResult<TVariant<TSharedPtr<HttpContent>, void*>>::Failure(TEXT("error calling SrcHandlersv2FilesGetBlob: unexpected response code"), Response.ResponseCode, Response.Headers);
}



THTTPResult<TVariant<TSharedPtr<FileEntry>, TSharedPtr<Error>>> RepositoryManipulationApi::SrcHandlersv2FilesGetFileEntry(FString repoId, FString refId, FString path, 
        const FString& Token,
        const TMap<FString, FString>& Headers,
		int ConnectionTimeoutSeconds, int RequestTimeoutSeconds) const
{

    FString URL = TEXT("/v0/repos/{repo_id}/files/{ref_id}/{path}");
    URL.ReplaceInline(TEXT("{repo_id}"), *DiversionHttp::URLEncode(DiversionHttp::parameterToString(repoId)));
    URL.ReplaceInline(TEXT("{ref_id}"), *DiversionHttp::URLEncode(DiversionHttp::parameterToString(refId)));
    URL.ReplaceInline(TEXT("{path}"), *DiversionHttp::URLEncode(DiversionHttp::parameterToString(path)));

    TMap<FString, FString> localVarQueryParams;
    TMap<FString, FString> localVarFormParams;
    //TMap<FString, TSharedPtr<HttpContent>> localVarFileParams;

    
    TSet<FString> localVarResponseHttpContentTypes;
    localVarResponseHttpContentTypes.Add(TEXT("application/json"));

    FString localVarResponseHttpContentType;

    // use JSON if possible
    if (localVarResponseHttpContentTypes.Num() == 0)
    {
        localVarResponseHttpContentType = TEXT("application/json");
    }
    // JSON
    else if (localVarResponseHttpContentTypes.Contains(TEXT("application/json")))
    {
        localVarResponseHttpContentType = TEXT("application/json");
    }
    else
    {
        return THTTPResult<TVariant<TSharedPtr<FileEntry>, TSharedPtr<Error>>>::Failure(TEXT("RepositoryManipulationApi->SrcHandlersv2FilesGetFileEntry does not produce any supported media type"), 400, {});
    }

    // TODO: Add this to the headers
    //Headers[TEXT("Accept")] = localVarResponseHttpContentType;

    TSet<FString> localVarConsumeHttpContentTypes;


    FString Content = TEXT("");
    // TSharedPtr<IHttpBody> localVarHttpBody;
    FString localVarRequestHttpContentType;

    // use JSON if possible
    if (localVarConsumeHttpContentTypes.Num() == 0 || localVarConsumeHttpContentTypes.Contains(TEXT("application/json")))
    {
        localVarRequestHttpContentType = TEXT("application/json");
    }
    else
    {
        return THTTPResult<TVariant<TSharedPtr<FileEntry>, TSharedPtr<Error>>>::Failure(TEXT("RepositoryManipulationApi->SrcHandlersv2FilesGetFileEntry does not consume any supported media type"), 415, {});
    }

    // Add query params
    if (localVarQueryParams.Num() > 0) {
        URL += TEXT("?");
        FString QueryParams;
        for (const auto& Param : localVarQueryParams)
        {
            QueryParams += Param.Key + TEXT("=") + Param.Value + TEXT("&");
        }
        QueryParams.RemoveFromEnd(TEXT("&"));
        URL += QueryParams;
    }

    DiversionHttp::HTTPCallResponse Response = ApiClient->SendRequest(URL, DiversionHttp::HttpMethod::GET, Token, localVarRequestHttpContentType, 
        Content, Headers, ConnectionTimeoutSeconds, RequestTimeoutSeconds);

    // TODO: Add validation - check response content type
    
    if (Response.ResponseCode == 200) {
        if(localVarResponseHttpContentType == TEXT("application/json"))
        {
            TSharedPtr<FileEntry> localVarResult = MakeShared<FileEntry>();
            TSharedPtr<FJsonValue> JsonValue;
            TSharedRef<TJsonReader<>> JsonReader = TJsonReaderFactory<>::Create(Response.Contents);
            if (!FJsonSerializer::Deserialize(JsonReader, JsonValue) || !JsonValue.IsValid())
            {
                return THTTPResult<TVariant<TSharedPtr<FileEntry>, TSharedPtr<Error>>>::Failure(TEXT("error calling src_handlersv2_files_getFileEntry: JSON reader failed parsing the response string"), 500, Response.Headers);
            }

            
            if (localVarResult->FromJson(JsonValue)) {
                TVariant<TSharedPtr<FileEntry>, TSharedPtr<Error>> variantResult;
                variantResult.Emplace<TSharedPtr<FileEntry>>(localVarResult);
                return THTTPResult<TVariant<TSharedPtr<FileEntry>, TSharedPtr<Error>>>::Success(TOptional(variantResult), Response.ResponseCode, Response.Headers);
            }
            else {
                return THTTPResult<TVariant<TSharedPtr<FileEntry>, TSharedPtr<Error>>>::Failure(TEXT("error calling src_handlersv2_files_getFileEntry: JSON response was not in the expected format"), 500, Response.Headers);
            }
        }


        else
        {
            return THTTPResult<TVariant<TSharedPtr<FileEntry>, TSharedPtr<Error>>>::Failure(TEXT("error calling src_handlersv2_files_getFileEntry: unsupported response type"), 500, Response.Headers);
        }
    }
    if (Response.ResponseCode == 404) {
            FString ErrorMessage = TEXT("General Failure");
            if(Response.Error.IsSet()) {
                ErrorMessage = Response.Error.GetValue();
            } 
            // Try parsing as JSON
            else if(!Response.Contents.IsEmpty()) {
                if(localVarResponseHttpContentType == TEXT("application/json"))
                {
                    TSharedPtr<Error> localVarResult = MakeShared<Error>();
                    TSharedPtr<FJsonValue> JsonValue;
                    TSharedRef<TJsonReader<>> JsonReader = TJsonReaderFactory<>::Create(Response.Contents);
                    if (!FJsonSerializer::Deserialize(JsonReader, JsonValue) || !JsonValue.IsValid())
                    {
                        ErrorMessage = TEXT("Received corrupted error data");
                    }
                    
                    if (localVarResult->FromJson(JsonValue)) {
                        TVariant<TSharedPtr<FileEntry>, TSharedPtr<Error>> variantResult;
                        variantResult.Emplace<TSharedPtr<Error>>(localVarResult);
                        return THTTPResult<TVariant<TSharedPtr<FileEntry>, TSharedPtr<Error>>>::Failure(TEXT("ParsedJsonError"), Response.ResponseCode, Response.Headers, TOptional(variantResult));
                    }
                    else {
                        ErrorMessage = TEXT("Received corrupted error data");
                    }
                }
            }
            FString CurrError = TEXT("error calling src_handlersv2_files_getFileEntry: ") + ErrorMessage;
            return THTTPResult<TVariant<TSharedPtr<FileEntry>, TSharedPtr<Error>>>::Failure(CurrError, Response.ResponseCode, Response.Headers);

    }
    if (Response.ResponseCode == 0) {
        if(localVarResponseHttpContentType == TEXT("application/json"))
        {
            TSharedPtr<Error> localVarResult = MakeShared<Error>();
            TSharedPtr<FJsonValue> JsonValue;
            TSharedRef<TJsonReader<>> JsonReader = TJsonReaderFactory<>::Create(Response.Contents);
            if (!FJsonSerializer::Deserialize(JsonReader, JsonValue) || !JsonValue.IsValid())
            {
                return THTTPResult<TVariant<TSharedPtr<FileEntry>, TSharedPtr<Error>>>::Failure(TEXT("error calling src_handlersv2_files_getFileEntry: JSON reader failed parsing the response string"), 500, Response.Headers);
            }

            
            if (localVarResult->FromJson(JsonValue)) {
                TVariant<TSharedPtr<FileEntry>, TSharedPtr<Error>> variantResult;
                variantResult.Emplace<TSharedPtr<Error>>(localVarResult);
                return THTTPResult<TVariant<TSharedPtr<FileEntry>, TSharedPtr<Error>>>::Success(TOptional(variantResult), Response.ResponseCode, Response.Headers);
            }
            else {
                return THTTPResult<TVariant<TSharedPtr<FileEntry>, TSharedPtr<Error>>>::Failure(TEXT("error calling src_handlersv2_files_getFileEntry: JSON response was not in the expected format"), 500, Response.Headers);
            }
        }


        else
        {
            return THTTPResult<TVariant<TSharedPtr<FileEntry>, TSharedPtr<Error>>>::Failure(TEXT("error calling src_handlersv2_files_getFileEntry: unsupported response type"), 500, Response.Headers);
        }
    }


    if (Response.ResponseCode >= 400)
    {
            FString ErrorMessage = TEXT("General Failure");
            if(Response.Error.IsSet()) {
                ErrorMessage = Response.Error.GetValue();
            } 
            else if(!Response.Contents.IsEmpty()) {
                // Try parsing as JSON
                TSharedPtr<FJsonObject> JsonObject;
                TSharedRef<TJsonReader<>> JsonReader = TJsonReaderFactory<>::Create(Response.Contents);
                if (FJsonSerializer::Deserialize(JsonReader, JsonObject) 
                    && JsonObject.IsValid())
                {
                    if (JsonObject->HasField(TEXT("error_message"))) {
                        ErrorMessage = JsonObject->GetStringField(TEXT("error_message"));
                    }
                    else {
                        // Treat it as an error string 
                        ErrorMessage = Response.Contents;
                    }
                }
                else {
                    // Treat it as an error string 
                    ErrorMessage = Response.Contents;
                }
            }

            FString CurrError = TEXT("error calling src_handlersv2_files_getFileEntry: ") + ErrorMessage;
            return THTTPResult<TVariant<TSharedPtr<FileEntry>, TSharedPtr<Error>>>::Failure(CurrError, Response.ResponseCode, Response.Headers);
    }

    // Unepxected response code - TODO: try parse as any of the expected response types
    return THTTPResult<TVariant<TSharedPtr<FileEntry>, TSharedPtr<Error>>>::Failure(TEXT("error calling SrcHandlersv2FilesGetFileEntry: unexpected response code"), Response.ResponseCode, Response.Headers);
}


}
}

