// Copyright 2024 Diversion Company, Inc. All Rights Reserved.
/**
 * Diversion Core API
 * Definition of the Core API used to access low-level functionality of Diversion
 *
 * The version of the OpenAPI document: 0.2.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.10.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "JsonBody.h"
#include "Src_handlersv2_repo_list_all_200_response.h"

namespace Diversion {
namespace CoreAPI {
namespace Model {



void Src_handlersv2_repo_list_all_200_response::WriteJson(JsonWriter& Writer) const
{
	Writer->WriteObjectStart();
	Writer->WriteIdentifierPrefix(TEXT("object")); WriteJsonValue(Writer, Src_handlersv2_repo_list_all_200_response::EnumToString(mobject));
	Writer->WriteIdentifierPrefix(TEXT("items")); WriteJsonValue(Writer, mItems);
	Writer->WriteObjectEnd();
}

bool Src_handlersv2_repo_list_all_200_response::FromJson(const TSharedPtr<FJsonValue>& JsonValue)
{

	const TSharedPtr<FJsonObject>* InnerGeneratorOpenAPIObject;
	if (!JsonValue->TryGetObject(InnerGeneratorOpenAPIObject))
		return false;

	bool ParseSuccess = true;

    

    // Reading the value into a string enum first
    FString objectString;
    bool ParseEnumobjectStringSuccess = TryGetJsonValue(*InnerGeneratorOpenAPIObject, TEXT("object"), objectString);
    if (ParseEnumobjectStringSuccess) {
        ParseSuccess &= Src_handlersv2_repo_list_all_200_response::EnumFromString(objectString, mobject);
        
    }
	ParseSuccess &= TryGetJsonValue(*InnerGeneratorOpenAPIObject, TEXT("items"), mItems);


	return ParseSuccess;
}


FString Src_handlersv2_repo_list_all_200_response::EnumToString(const ObjectEnum& EnumValue) {
    switch (EnumValue)
    {
    case ObjectEnum::REPO:
        return TEXT("REPO");
    default:
        return TEXT("");
    }
}

bool Src_handlersv2_repo_list_all_200_response::EnumFromString(const FString& EnumAsString, ObjectEnum& EnumValue) {
    if(EnumAsString.IsEmpty()) return false;
    if(EnumAsString == TEXT("REPO")) {
        EnumValue = ObjectEnum::REPO;
        return true;
    }

    return false;
}


}
}
}

