// Copyright 2024 Diversion Company, Inc. All Rights Reserved.
/**
 * Diversion Core API
 * Definition of the Core API used to access low-level functionality of Diversion
 *
 * The version of the OpenAPI document: 0.2.0
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.10.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "JsonBody.h"
#include "Workspace.h"

namespace Diversion {
namespace CoreAPI {
namespace Model {



void Workspace::WriteJson(JsonWriter& Writer) const
{
	Writer->WriteObjectStart();
	Writer->WriteIdentifierPrefix(TEXT("workspace_id")); WriteJsonValue(Writer, mWorkspace_id);
	if (mName.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("name")); WriteJsonValue(Writer, mName.GetValue());
	}
	if (mSource_commit.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("source_commit")); WriteJsonValue(Writer, mSource_commit.GetValue());
	}
	if (mBranch_id.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("branch_id")); WriteJsonValue(Writer, mBranch_id.GetValue());
	}
	Writer->WriteIdentifierPrefix(TEXT("base_commit_id")); WriteJsonValue(Writer, mBase_commit_id);
	Writer->WriteIdentifierPrefix(TEXT("repo_id")); WriteJsonValue(Writer, mRepo_id);
	Writer->WriteIdentifierPrefix(TEXT("journal_ordinal_id")); WriteJsonValue(Writer, mJournal_ordinal_id);
	if (mClient_id.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("client_id")); WriteJsonValue(Writer, mClient_id.GetValue());
	}
	Writer->WriteObjectEnd();
}

bool Workspace::FromJson(const TSharedPtr<FJsonValue>& JsonValue)
{

	const TSharedPtr<FJsonObject>* InnerGeneratorOpenAPIObject;
	if (!JsonValue->TryGetObject(InnerGeneratorOpenAPIObject))
		return false;

	bool ParseSuccess = true;

    

	ParseSuccess &= TryGetJsonValue(*InnerGeneratorOpenAPIObject, TEXT("workspace_id"), mWorkspace_id);
    ParseSuccess &= TryGetJsonValue(*InnerGeneratorOpenAPIObject, TEXT("name"), mName);
    ParseSuccess &= TryGetJsonValue(*InnerGeneratorOpenAPIObject, TEXT("source_commit"), mSource_commit);
    ParseSuccess &= TryGetJsonValue(*InnerGeneratorOpenAPIObject, TEXT("branch_id"), mBranch_id);
	ParseSuccess &= TryGetJsonValue(*InnerGeneratorOpenAPIObject, TEXT("base_commit_id"), mBase_commit_id);
	ParseSuccess &= TryGetJsonValue(*InnerGeneratorOpenAPIObject, TEXT("repo_id"), mRepo_id);
	ParseSuccess &= TryGetJsonValue(*InnerGeneratorOpenAPIObject, TEXT("journal_ordinal_id"), mJournal_ordinal_id);
    ParseSuccess &= TryGetJsonValue(*InnerGeneratorOpenAPIObject, TEXT("client_id"), mClient_id);


	return ParseSuccess;
}


}
}
}

